from setuptools import setup, find_packages
 
with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()
 
setup(
    name="fastpix_python",
    version="1.1.2",
    packages=find_packages(),
    install_requires=[
        "httpcore>=1.0.9",
        "httpx>=0.28.1",
        "pydantic>=2.11.2",
    ],
    description="Python Client SDK Generated by fastpix.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="FastPix",
    author_email="devs@fastpix.io",
    url="https://github.com/FastPix/fastpix-python",
    project_urls={
        "GitHub": "https://github.com/FastPix/fastpix-python",
        "Website": "https://fastpix.io",
        "Dashboard": "https://dashboard.fastpix.io",
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
    python_requires=">=3.9.2",
)