"""Code generated by fastpix (https://fastpix.com). DO NOT EDIT."""

from __future__ import annotations
from .playbackid import PlaybackID, PlaybackIDTypedDict
from ..types import BaseModel
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DirectUploadResponseTypedDict(TypedDict):
    media_quality: NotRequired[str]
    r"""The media quality tier (e.g. ``"pro"``)."""
    metadata: NotRequired[Dict[str, str]]
    r"""You can search for videos with specific key value pairs using metadata, when you tag a video in \"key\" : \"value\" pairs."""
    optimize_audio: NotRequired[bool]
    r"""Whether audio normalization is enabled for the resulting media."""
    playback_ids: NotRequired[List[PlaybackIDTypedDict]]
    source_access: NotRequired[bool]
    r"""Whether the original source file is accessible after processing."""


class DirectUploadResponse(BaseModel):
    media_quality: Annotated[Optional[str], pydantic.Field(alias="mediaQuality")] = None
    r"""The media quality tier (e.g. ``"pro"``)."""

    metadata: Optional[Dict[str, str]] = None
    r"""You can search for videos with specific key value pairs using metadata, when you tag a video in \"key\" : \"value\" pairs."""

    optimize_audio: Annotated[Optional[bool], pydantic.Field(alias="optimizeAudio")] = None
    r"""Whether audio normalization is enabled for the resulting media."""

    playback_ids: Annotated[
        Optional[List[PlaybackID]], pydantic.Field(alias="playbackIds")
    ] = None

    source_access: Annotated[Optional[bool], pydantic.Field(alias="sourceAccess")] = None
    r"""Whether the original source file is accessible after processing."""
