"""Code generated by fastpix (https://fastpix.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


MediaType = Literal[
    "video",
    "audio",
    "av",
]
r"""Type of media content"""
