"""Code generated by fastpix (https://fastpix.com). DO NOT EDIT."""

from __future__ import annotations
from ..types import BaseModel
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypedDict


class ItemTypedDict(TypedDict, total=False):
    value: Union[int, float]
    r"""The specific metric value calculated based on the applied filters."""
    type: str
    r"""value can be score that ranges from 0 to 100"""
    name: str
    r"""value can be score that ranges from 0 to 100"""
    metric: str
    r"""The KPI being tracked or analyzed."""
    measurement: str
    r"""Aggregation function used for the metric (e.g. ``avg``, ``sum``, ``count``)."""
    items: List["ItemTypedDict"]
    r"""Nested breakdown of related metrics."""


class Item(BaseModel):
    value: Optional[Union[int, float]] = None
    r"""The specific metric value calculated based on the applied filters."""

    type: Optional[str] = None
    r"""value can be score that ranges from 0 to 100"""

    name: Optional[str] = None
    r"""value can be score that ranges from 0 to 100"""

    metric: Optional[str] = None
    r"""The KPI being tracked or analyzed."""

    measurement: Optional[str] = None
    r"""Aggregation function used for the metric (e.g. ``avg``, ``sum``, ``count``)."""

    items: Optional[List["Item"]] = None
    r"""Nested breakdown of related metrics."""


class MetricsComparisonDetailsTypedDict(TypedDict, total=False):
    value: Union[int, float]
    type: str
    name: str
    metric: str
    measurement: str
    items: List[ItemTypedDict]


class MetricsComparisonDetails(BaseModel):
    value: Optional[Union[int, float]] = None

    type: Optional[str] = None

    name: Optional[str] = None

    metric: Optional[str] = None

    measurement: Optional[str] = None
    r"""Aggregation function (e.g. ``avg``, ``sum``, ``count``, ``95th``)."""

    items: Optional[List[Item]] = None
    r"""Nested breakdown of related metrics for more detailed analysis."""


Item.model_rebuild()
