"""Code generated by fastpix (https://fastpix.com). DO NOT EDIT."""

from __future__ import annotations
from .playbackidresponse import (
    PlaybackIDAccessRestrictions,
    PlaybackIDAccessRestrictionsTypedDict,
)
from ..types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlaybackIDSuccessResponseDataTypedDict(TypedDict):
    id: NotRequired[str]
    r"""Unique identifier for the playbackId"""
    access_policy: NotRequired[str]
    r"""Determines if access to the streamed content is kept private or available to all."""
    access_restrictions: NotRequired[PlaybackIDAccessRestrictionsTypedDict]
    r"""Optional domain and user-agent access restrictions applied to the playback ID."""


class PlaybackIDSuccessResponseData(BaseModel):
    id: Optional[str] = None
    r"""Unique identifier for the playbackId"""

    access_policy: Annotated[Optional[str], pydantic.Field(alias="accessPolicy")] = None
    r"""Determines if access to the streamed content is kept private or available to all."""

    access_restrictions: Annotated[
        Optional[PlaybackIDAccessRestrictions],
        pydantic.Field(alias="accessRestrictions"),
    ] = None
    r"""Optional domain and user-agent access restrictions applied to the playback ID."""


class PlaybackIDSuccessResponseTypedDict(TypedDict):
    r"""Displays the result of the request."""

    success: NotRequired[bool]
    r"""It demonstrates whether the request is successful or not."""
    data: NotRequired[PlaybackIDSuccessResponseDataTypedDict]


class PlaybackIDSuccessResponse(BaseModel):
    r"""Displays the result of the request."""

    success: Optional[bool] = None
    r"""It demonstrates whether the request is successful or not."""

    data: Optional[PlaybackIDSuccessResponseData] = None
