"""Code generated by fastpix (https://fastpix.com). DO NOT EDIT."""

from __future__ import annotations
from ..types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SuccessResponseDataTypedDict(TypedDict):
    pass


class SuccessResponseData(BaseModel):
    pass


class SuccessResponseTypedDict(TypedDict):
    success: bool
    r"""Demonstrates whether the request is successful or not."""
    data: NotRequired[List[SuccessResponseDataTypedDict]]
    r"""Optional — many delete endpoints return only ``{"success": true}`` with no data array."""


class SuccessResponse(BaseModel):
    success: bool
    r"""Demonstrates whether the request is successful or not."""

    data: Optional[List[SuccessResponseData]] = None
    r"""Optional — many delete endpoints return only ``{"success": true}`` with no data array."""
