"""Code generated by fastpix (https://fastpix.com). DO NOT EDIT."""

from __future__ import annotations
from ..types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SummaryResponseTypedDict(TypedDict):
    media_id: NotRequired[str]
    is_generated_summary: NotRequired[bool]
    r"""Alias of isSummaryEnabled."""


class SummaryResponse(BaseModel):
    media_id: Annotated[Optional[str], pydantic.Field(alias="mediaId")] = None

    is_generated_summary: Annotated[
        Optional[bool], pydantic.Field(alias="isSummaryEnabled")
    ] = None
