"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from ..types import BaseModel, UNSET_SENTINEL
from ..utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


UpdateLiveStreamUserAgentRestrictionsDefaultPolicy = Literal[
    "allow",
    "deny",
]
r"""The default behavior when a user-agent is not listed in `allow` or `deny`."""


class UpdateLiveStreamUserAgentRestrictionsRequestBodyTypedDict(TypedDict):
    default_policy: NotRequired[UpdateLiveStreamUserAgentRestrictionsDefaultPolicy]
    r"""The default behavior when a user-agent is not listed in `allow` or `deny`."""
    allow: NotRequired[List[str]]
    r"""List of user-agent substrings explicitly allowed."""
    deny: NotRequired[List[str]]
    r"""List of user-agent substrings explicitly denied."""


class UpdateLiveStreamUserAgentRestrictionsRequestBody(BaseModel):
    default_policy: Annotated[
        Optional[UpdateLiveStreamUserAgentRestrictionsDefaultPolicy],
        pydantic.Field(alias="defaultPolicy"),
    ] = "allow"
    r"""The default behavior when a user-agent is not listed in `allow` or `deny`."""

    allow: Optional[List[str]] = None
    r"""List of user-agent substrings explicitly allowed."""

    deny: Optional[List[str]] = None
    r"""List of user-agent substrings explicitly denied."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"defaultPolicy", "allow", "deny"}
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL and (
                val is not None or k not in optional_fields
            ):
                m[k] = val

        return m


class UpdateLiveStreamUserAgentRestrictionsRequestTypedDict(TypedDict):
    stream_id: str
    playback_id: str
    body: UpdateLiveStreamUserAgentRestrictionsRequestBodyTypedDict


class UpdateLiveStreamUserAgentRestrictionsRequest(BaseModel):
    stream_id: Annotated[
        str,
        pydantic.Field(alias="streamId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    playback_id: Annotated[
        str,
        pydantic.Field(alias="playbackId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        UpdateLiveStreamUserAgentRestrictionsRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class UpdateLiveStreamUserAgentRestrictionsDataTypedDict(TypedDict):
    default_policy: NotRequired[str]
    r"""Specifies the default behavior for user agents not listed in the allow or deny lists."""
    allow: NotRequired[List[str]]
    r"""List of user-agent substrings explicitly allowed."""
    deny: NotRequired[List[str]]
    r"""List of user-agent substrings explicitly denied."""


class UpdateLiveStreamUserAgentRestrictionsData(BaseModel):
    default_policy: Annotated[Optional[str], pydantic.Field(alias="defaultPolicy")] = (
        None
    )
    r"""Specifies the default behavior for user agents not listed in the allow or deny lists."""

    allow: Optional[List[str]] = None
    r"""List of user-agent substrings explicitly allowed."""

    deny: Optional[List[str]] = None
    r"""List of user-agent substrings explicitly denied."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"defaultPolicy", "allow", "deny"}
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL and (
                val is not None or k not in optional_fields
            ):
                m[k] = val

        return m


class UpdateLiveStreamUserAgentRestrictionsResponseBodyTypedDict(TypedDict):
    r"""Successfully updated user-agent restrictions"""

    success: NotRequired[bool]
    r"""Shows the request status. Returns true for success and false for failure."""
    data: NotRequired[UpdateLiveStreamUserAgentRestrictionsDataTypedDict]


class UpdateLiveStreamUserAgentRestrictionsResponseBody(BaseModel):
    r"""Successfully updated user-agent restrictions"""

    success: Optional[bool] = None
    r"""Shows the request status. Returns true for success and false for failure."""

    data: Optional[UpdateLiveStreamUserAgentRestrictionsData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"success", "data"}
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL and (
                val is not None or k not in optional_fields
            ):
                m[k] = val

        return m


UpdateLiveStreamUserAgentRestrictionsResponseTypedDict = TypeAliasType(
    "UpdateLiveStreamUserAgentRestrictionsResponseTypedDict",
    Union[UpdateLiveStreamUserAgentRestrictionsResponseBodyTypedDict, DefaultErrorTypedDict],
)


UpdateLiveStreamUserAgentRestrictionsResponse = TypeAliasType(
    "UpdateLiveStreamUserAgentRestrictionsResponse",
    Union[UpdateLiveStreamUserAgentRestrictionsResponseBody, DefaultError],
)
