"""Code generated by fastpix (https://fastpix.com). DO NOT EDIT."""

from .basesdk import BaseSDK, BuildRequestData
from . import errors, models, utils
from ._hooks import HookContext
from .types import OptionalNullable, UNSET
from .utils import get_security_from_env
from .utils.unmarshal_json_response import unmarshal_json_response
from typing import List, Mapping, NoReturn, Optional, Union

CONTENT_TYPE_JSON = "application/json"
API_ERROR_MESSAGE = "API error occurred"
UNEXPECTED_RESPONSE_MESSAGE = "Unexpected response received"
PLAYBACK_IDS_PATH = "/live/streams/{streamId}/playback-ids"


class LivePlayback(BaseSDK):
    def _raise_for_status(self, http_res, error_map) -> NoReturn:
        for status, error_data_cls, error_cls in error_map:
            if utils.match_response(http_res, status, CONTENT_TYPE_JSON):
                response_data = unmarshal_json_response(error_data_cls, http_res)
                raise error_cls(response_data, http_res)
        if utils.match_response(http_res, ["4XX", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.FastpixDefaultError(
                API_ERROR_MESSAGE, http_res, http_res_text
            )
        raise errors.FastpixDefaultError(UNEXPECTED_RESPONSE_MESSAGE, http_res)

    async def _raise_for_status_async(self, http_res, error_map) -> NoReturn:
        for status, error_data_cls, error_cls in error_map:
            if utils.match_response(http_res, status, CONTENT_TYPE_JSON):
                response_data = unmarshal_json_response(error_data_cls, http_res)
                raise error_cls(response_data, http_res)
        if utils.match_response(http_res, ["4XX", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.FastpixDefaultError(
                API_ERROR_MESSAGE, http_res, http_res_text
            )
        raise errors.FastpixDefaultError(UNEXPECTED_RESPONSE_MESSAGE, http_res)

    def create_playback_id_of_stream(
        self,
        *,
        stream_id: str,
        access_policy: Optional[models.BasicAccessPolicy] = None,
        access_restrictions: Optional[
            Union[
                models.PlaybackIDAccessRestrictions,
                models.PlaybackIDAccessRestrictionsTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PlaybackIDSuccessResponse:
        r"""Create a playbackId

        Generates a new playback ID for the live stream, allowing viewers to access the stream through this ID. The playback ID can be shared with viewers for direct access to the live broadcast.

        By calling this endpoint with the `streamId`, FastPix returns a unique `playbackId`, which can be used to stream the live content.

        #### Example

        A media platform needs to distribute a unique playback ID to users for an exclusive live concert. The platform can also embed the stream on various partner websites.

        :param stream_id: Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
        :param access_policy: Basic access policy for media content
        :param access_restrictions: Optional domain and user-agent access restrictions applied to the playback ID.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreatePlaybackIDOfStreamRequest(
            stream_id=stream_id,
            playback_id_request=models.PlaybackIDRequest(
                access_policy=access_policy,
                access_restrictions=access_restrictions,
            ),
        )

        req = self._build_request(BuildRequestData(
            method="POST",
            path=PLAYBACK_IDS_PATH,
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=CONTENT_TYPE_JSON,
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.playback_id_request,
                False,
                False,
                "json",
                models.PlaybackIDRequest,
            ),
            timeout_ms=timeout_ms,
        ))

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(1000, 10000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["408", "429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="create-playbackId-of-stream",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "403", "404", "422", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "201", CONTENT_TYPE_JSON):
            return unmarshal_json_response(models.PlaybackIDSuccessResponse, http_res)
        self._raise_for_status(
            http_res,
            [
                ("401", errors.UnauthorizedErrorData, errors.UnauthorizedError),
                ("403", errors.InvalidPermissionErrorData, errors.InvalidPermissionError),
                ("404", errors.LiveNotFoundErrorData, errors.LiveNotFoundError),
                ("422", errors.ValidationErrorResponseData, errors.ValidationErrorResponse),
            ],
        )

    async def create_playback_id_of_stream_async(
        self,
        *,
        stream_id: str,
        access_policy: Optional[models.BasicAccessPolicy] = None,
        access_restrictions: Optional[
            Union[
                models.PlaybackIDAccessRestrictions,
                models.PlaybackIDAccessRestrictionsTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PlaybackIDSuccessResponse:
        r"""Create a playbackId

        Generates a new playback ID for the live stream, allowing viewers to access the stream through this ID. The playback ID can be shared with viewers for direct access to the live broadcast.

        By calling this endpoint with the `streamId`, FastPix returns a unique `playbackId`, which can be used to stream the live content.

        #### Example

        A media platform needs to distribute a unique playback ID to users for an exclusive live concert. The platform can also embed the stream on various partner websites.

        :param stream_id: Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
        :param access_policy: Basic access policy for media content
        :param access_restrictions: Optional domain and user-agent access restrictions applied to the playback ID.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreatePlaybackIDOfStreamRequest(
            stream_id=stream_id,
            playback_id_request=models.PlaybackIDRequest(
                access_policy=access_policy,
                access_restrictions=access_restrictions,
            ),
        )

        req = self._build_request_async(BuildRequestData(
            method="POST",
            path=PLAYBACK_IDS_PATH,
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=CONTENT_TYPE_JSON,
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.playback_id_request,
                False,
                False,
                "json",
                models.PlaybackIDRequest,
            ),
            timeout_ms=timeout_ms,
        ))

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(1000, 10000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["408", "429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="create-playbackId-of-stream",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "403", "404", "422", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "201", CONTENT_TYPE_JSON):
            return unmarshal_json_response(models.PlaybackIDSuccessResponse, http_res)
        await self._raise_for_status_async(
            http_res,
            [
                ("401", errors.UnauthorizedErrorData, errors.UnauthorizedError),
                ("403", errors.InvalidPermissionErrorData, errors.InvalidPermissionError),
                ("404", errors.LiveNotFoundErrorData, errors.LiveNotFoundError),
                ("422", errors.ValidationErrorResponseData, errors.ValidationErrorResponse),
            ],
        )

    def delete_playback_id_of_stream(
        self,
        *,
        stream_id: str,
        playback_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.LiveStreamDeleteResponse:
        r"""Delete a playbackId

        Deletes a previously created playback ID for a live stream. This will prevent any new viewers from accessing the stream through the playback ID, though current viewers will be able to continue watching for a limited time before being disconnected. By providing the `playbackId`, FastPix deletes the ID and ensures new playback requests will fail.

        #### Example
        A streaming service wants to prevent new users from joining a live stream that is nearing its end. The host can delete the playback ID to ensure no one can join the stream or replay it once it ends.

        :param stream_id: Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
        :param playback_id: Unique identifier for the playbackId
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DeletePlaybackIDOfStreamRequest(
            stream_id=stream_id,
            playback_id=playback_id,
        )

        req = self._build_request(BuildRequestData(
            method="DELETE",
            path=PLAYBACK_IDS_PATH,
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=CONTENT_TYPE_JSON,
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        ))

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(1000, 10000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["408", "429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="delete-playbackId-of-stream",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "403", "404", "422", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", CONTENT_TYPE_JSON):
            return unmarshal_json_response(models.LiveStreamDeleteResponse, http_res)
        self._raise_for_status(
            http_res,
            [
                ("401", errors.UnauthorizedErrorData, errors.UnauthorizedError),
                ("403", errors.InvalidPermissionErrorData, errors.InvalidPermissionError),
                ("404", errors.NotFoundErrorPlaybackIDData, errors.NotFoundErrorPlaybackID),
                ("422", errors.ValidationErrorResponseData, errors.ValidationErrorResponse),
            ],
        )

    async def delete_playback_id_of_stream_async(
        self,
        *,
        stream_id: str,
        playback_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.LiveStreamDeleteResponse:
        r"""Delete a playbackId

        Deletes a previously created playback ID for a live stream. This will prevent any new viewers from accessing the stream through the playback ID, though current viewers will be able to continue watching for a limited time before being disconnected. By providing the `playbackId`, FastPix deletes the ID and ensures new playback requests will fail.

        #### Example
        A streaming service wants to prevent new users from joining a live stream that is nearing its end. The host can delete the playback ID to ensure no one can join the stream or replay it once it ends.

        :param stream_id: Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
        :param playback_id: Unique identifier for the playbackId
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DeletePlaybackIDOfStreamRequest(
            stream_id=stream_id,
            playback_id=playback_id,
        )

        req = self._build_request_async(BuildRequestData(
            method="DELETE",
            path=PLAYBACK_IDS_PATH,
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=CONTENT_TYPE_JSON,
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        ))

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(1000, 10000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["408", "429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="delete-playbackId-of-stream",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "403", "404", "422", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", CONTENT_TYPE_JSON):
            return unmarshal_json_response(models.LiveStreamDeleteResponse, http_res)
        await self._raise_for_status_async(
            http_res,
            [
                ("401", errors.UnauthorizedErrorData, errors.UnauthorizedError),
                ("403", errors.InvalidPermissionErrorData, errors.InvalidPermissionError),
                ("404", errors.NotFoundErrorPlaybackIDData, errors.NotFoundErrorPlaybackID),
                ("422", errors.ValidationErrorResponseData, errors.ValidationErrorResponse),
            ],
        )

    def get_live_stream_playback_id(
        self,
        *,
        stream_id: str,
        playback_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PlaybackIDSuccessResponse:
        r"""Get playbackId details

        Retrieves details about a previously created playback ID. If you provide the distinct `playbackId` that was given back to you in the previous stream or create playbackId request, FastPix will provide the relevant playback details such as the access policy.

        #### Example
        A developer needs to confirm the access policy of the playback ID to ensure whether the stream is public or private for viewers.

        :param stream_id: Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
        :param playback_id: Upon creating a new playbackId, FastPix assigns a unique identifier to the playback.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetLiveStreamPlaybackIDRequest(
            stream_id=stream_id,
            playback_id=playback_id,
        )

        req = self._build_request(BuildRequestData(
            method="GET",
            path="/live/streams/{streamId}/playback-ids/{playbackId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=CONTENT_TYPE_JSON,
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        ))

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(1000, 10000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["408", "429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get-live-stream-playback-id",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "403", "404", "422", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", CONTENT_TYPE_JSON):
            return unmarshal_json_response(models.PlaybackIDSuccessResponse, http_res)
        self._raise_for_status(
            http_res,
            [
                ("401", errors.UnauthorizedErrorData, errors.UnauthorizedError),
                ("403", errors.InvalidPermissionErrorData, errors.InvalidPermissionError),
                ("404", errors.NotFoundErrorPlaybackIDData, errors.NotFoundErrorPlaybackID),
                ("422", errors.ValidationErrorResponseData, errors.ValidationErrorResponse),
            ],
        )

    async def get_live_stream_playback_id_async(
        self,
        *,
        stream_id: str,
        playback_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PlaybackIDSuccessResponse:
        r"""Get playbackId details

        Retrieves details about a previously created playback ID. If you provide the distinct `playbackId` that was given back to you in the previous stream or create playbackId request, FastPix will provide the relevant playback details such as the access policy.

        #### Example
        A developer needs to confirm the access policy of the playback ID to ensure whether the stream is public or private for viewers.

        :param stream_id: Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
        :param playback_id: Upon creating a new playbackId, FastPix assigns a unique identifier to the playback.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetLiveStreamPlaybackIDRequest(
            stream_id=stream_id,
            playback_id=playback_id,
        )

        req = self._build_request_async(BuildRequestData(
            method="GET",
            path="/live/streams/{streamId}/playback-ids/{playbackId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=CONTENT_TYPE_JSON,
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        ))

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(1000, 10000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["408", "429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get-live-stream-playback-id",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "403", "404", "422", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", CONTENT_TYPE_JSON):
            return unmarshal_json_response(models.PlaybackIDSuccessResponse, http_res)
        await self._raise_for_status_async(
            http_res,
            [
                ("401", errors.UnauthorizedErrorData, errors.UnauthorizedError),
                ("403", errors.InvalidPermissionErrorData, errors.InvalidPermissionError),
                ("404", errors.NotFoundErrorPlaybackIDData, errors.NotFoundErrorPlaybackID),
                ("422", errors.ValidationErrorResponseData, errors.ValidationErrorResponse),
            ],
        )

    def update_live_stream_domain_restrictions(
        self,
        *,
        stream_id: str,
        playback_id: str,
        default_policy: Optional[
            models.UpdateLiveStreamDomainRestrictionsDefaultPolicy
        ] = "allow",
        allow: Optional[List[str]] = None,
        deny: Optional[List[str]] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateLiveStreamDomainRestrictionsResponseBody:
        r"""Update domain restrictions for a playback ID

        This endpoint updates domain-level restrictions for a specific playback ID associated with a live stream.
        It allows you to restrict playback to specific domains or block known unauthorized domains.

        **How it works:**
        1. Make a `PATCH` request to this endpoint with your desired domain access configuration.
        2. Set a default policy (`allow` or `deny`) and specify domain names in the `allow` or `deny` lists.
        3. This is commonly used to restrict video playback to your website or approved client domains.

        **Example:**
        A streaming service can allow playback only from `example.com` and deny all others by setting: `\"defaultPolicy\": \"deny\"` and `\"allow\": [\"example.com\"]`.


        :param stream_id:
        :param playback_id:
        :param default_policy: Specify the fallback behavior for domains that are not listed in the `allow` or `deny` lists.
        :param allow: List of domains explicitly allowed to play the media.
        :param deny: List of domains explicitly denied from accessing the media.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UpdateLiveStreamDomainRestrictionsRequest(
            stream_id=stream_id,
            playback_id=playback_id,
            body=models.UpdateLiveStreamDomainRestrictionsRequestBody(
                default_policy=default_policy,
                allow=allow,
                deny=deny,
            ),
        )

        req = self._build_request(BuildRequestData(
            method="PATCH",
            path="/live/streams/{streamId}/playback-ids/{playbackId}/domains",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=CONTENT_TYPE_JSON,
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.UpdateLiveStreamDomainRestrictionsRequestBody,
            ),
            timeout_ms=timeout_ms,
        ))

        if retries == UNSET and self.sdk_configuration.retry_config is not UNSET:
            retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="update-live-stream-domain-restrictions",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", CONTENT_TYPE_JSON):
            return unmarshal_json_response(
                models.UpdateLiveStreamDomainRestrictionsResponseBody, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.FastpixDefaultError(
                API_ERROR_MESSAGE, http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.FastpixDefaultError(
                API_ERROR_MESSAGE, http_res, http_res_text
            )
        if utils.match_response(http_res, "default", CONTENT_TYPE_JSON):
            return unmarshal_json_response(models.DefaultError, http_res)

        raise errors.FastpixDefaultError(UNEXPECTED_RESPONSE_MESSAGE, http_res)

    async def update_live_stream_domain_restrictions_async(
        self,
        *,
        stream_id: str,
        playback_id: str,
        default_policy: Optional[
            models.UpdateLiveStreamDomainRestrictionsDefaultPolicy
        ] = "allow",
        allow: Optional[List[str]] = None,
        deny: Optional[List[str]] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateLiveStreamDomainRestrictionsResponseBody:
        r"""Update domain restrictions for a playback ID

        This endpoint updates domain-level restrictions for a specific playback ID associated with a live stream.
        It allows you to restrict playback to specific domains or block known unauthorized domains.

        **How it works:**
        1. Make a `PATCH` request to this endpoint with your desired domain access configuration.
        2. Set a default policy (`allow` or `deny`) and specify domain names in the `allow` or `deny` lists.
        3. This is commonly used to restrict video playback to your website or approved client domains.

        **Example:**
        A streaming service can allow playback only from `example.com` and deny all others by setting: `\"defaultPolicy\": \"deny\"` and `\"allow\": [\"example.com\"]`.


        :param stream_id:
        :param playback_id:
        :param default_policy: Specify the fallback behavior for domains that are not listed in the `allow` or `deny` lists.
        :param allow: List of domains explicitly allowed to play the media.
        :param deny: List of domains explicitly denied from accessing the media.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UpdateLiveStreamDomainRestrictionsRequest(
            stream_id=stream_id,
            playback_id=playback_id,
            body=models.UpdateLiveStreamDomainRestrictionsRequestBody(
                default_policy=default_policy,
                allow=allow,
                deny=deny,
            ),
        )

        req = self._build_request_async(BuildRequestData(
            method="PATCH",
            path="/live/streams/{streamId}/playback-ids/{playbackId}/domains",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=CONTENT_TYPE_JSON,
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.UpdateLiveStreamDomainRestrictionsRequestBody,
            ),
            timeout_ms=timeout_ms,
        ))

        if retries == UNSET and self.sdk_configuration.retry_config is not UNSET:
            retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="update-live-stream-domain-restrictions",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", CONTENT_TYPE_JSON):
            return unmarshal_json_response(
                models.UpdateLiveStreamDomainRestrictionsResponseBody, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.FastpixDefaultError(
                API_ERROR_MESSAGE, http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.FastpixDefaultError(
                API_ERROR_MESSAGE, http_res, http_res_text
            )
        if utils.match_response(http_res, "default", CONTENT_TYPE_JSON):
            return unmarshal_json_response(models.DefaultError, http_res)

        raise errors.FastpixDefaultError(UNEXPECTED_RESPONSE_MESSAGE, http_res)

    def update_live_stream_user_agent_restrictions(
        self,
        *,
        stream_id: str,
        playback_id: str,
        default_policy: Optional[
            models.UpdateLiveStreamUserAgentRestrictionsDefaultPolicy
        ] = "allow",
        allow: Optional[List[str]] = None,
        deny: Optional[List[str]] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateLiveStreamUserAgentRestrictionsResponseBody:
        r"""Update user-agent restrictions for a playback ID

        This endpoint allows updating user-agent restrictions for a specific playback ID associated with a live stream.
        It can be used to allow or deny specific user-agents during playback request evaluation.

        **How it works:**
        1. Make a `PATCH` request to this endpoint with your desired user-agent access configuration.
        2. Specify a default policy (`allow` or `deny`) and provide specific `allow` or `deny` lists.
        3. Use this to restrict access to specific browsers, devices, or bots.

        **Example:**
        A developer may configure a playback ID to deny access from known scraping user-agents while allowing all others by default.


        :param stream_id:
        :param playback_id:
        :param default_policy: The default behavior when a user-agent is not listed in `allow` or `deny`.
        :param allow: List of user-agent substrings explicitly allowed.
        :param deny: List of user-agent substrings explicitly denied.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UpdateLiveStreamUserAgentRestrictionsRequest(
            stream_id=stream_id,
            playback_id=playback_id,
            body=models.UpdateLiveStreamUserAgentRestrictionsRequestBody(
                default_policy=default_policy,
                allow=allow,
                deny=deny,
            ),
        )

        req = self._build_request(BuildRequestData(
            method="PATCH",
            path="/live/streams/{streamId}/playback-ids/{playbackId}/user-agents",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=CONTENT_TYPE_JSON,
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.UpdateLiveStreamUserAgentRestrictionsRequestBody,
            ),
            timeout_ms=timeout_ms,
        ))

        if retries == UNSET and self.sdk_configuration.retry_config is not UNSET:
            retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="update-live-stream-user-agent-restrictions",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", CONTENT_TYPE_JSON):
            return unmarshal_json_response(
                models.UpdateLiveStreamUserAgentRestrictionsResponseBody, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.FastpixDefaultError(
                API_ERROR_MESSAGE, http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.FastpixDefaultError(
                API_ERROR_MESSAGE, http_res, http_res_text
            )
        if utils.match_response(http_res, "default", CONTENT_TYPE_JSON):
            return unmarshal_json_response(models.DefaultError, http_res)

        raise errors.FastpixDefaultError(UNEXPECTED_RESPONSE_MESSAGE, http_res)

    async def update_live_stream_user_agent_restrictions_async(
        self,
        *,
        stream_id: str,
        playback_id: str,
        default_policy: Optional[
            models.UpdateLiveStreamUserAgentRestrictionsDefaultPolicy
        ] = "allow",
        allow: Optional[List[str]] = None,
        deny: Optional[List[str]] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateLiveStreamUserAgentRestrictionsResponseBody:
        r"""Update user-agent restrictions for a playback ID

        This endpoint allows updating user-agent restrictions for a specific playback ID associated with a live stream.
        It can be used to allow or deny specific user-agents during playback request evaluation.

        **How it works:**
        1. Make a `PATCH` request to this endpoint with your desired user-agent access configuration.
        2. Specify a default policy (`allow` or `deny`) and provide specific `allow` or `deny` lists.
        3. Use this to restrict access to specific browsers, devices, or bots.

        **Example:**
        A developer may configure a playback ID to deny access from known scraping user-agents while allowing all others by default.


        :param stream_id:
        :param playback_id:
        :param default_policy: The default behavior when a user-agent is not listed in `allow` or `deny`.
        :param allow: List of user-agent substrings explicitly allowed.
        :param deny: List of user-agent substrings explicitly denied.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UpdateLiveStreamUserAgentRestrictionsRequest(
            stream_id=stream_id,
            playback_id=playback_id,
            body=models.UpdateLiveStreamUserAgentRestrictionsRequestBody(
                default_policy=default_policy,
                allow=allow,
                deny=deny,
            ),
        )

        req = self._build_request_async(BuildRequestData(
            method="PATCH",
            path="/live/streams/{streamId}/playback-ids/{playbackId}/user-agents",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=CONTENT_TYPE_JSON,
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.UpdateLiveStreamUserAgentRestrictionsRequestBody,
            ),
            timeout_ms=timeout_ms,
        ))

        if retries == UNSET and self.sdk_configuration.retry_config is not UNSET:
            retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="update-live-stream-user-agent-restrictions",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", CONTENT_TYPE_JSON):
            return unmarshal_json_response(
                models.UpdateLiveStreamUserAgentRestrictionsResponseBody, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.FastpixDefaultError(
                API_ERROR_MESSAGE, http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.FastpixDefaultError(
                API_ERROR_MESSAGE, http_res, http_res_text
            )
        if utils.match_response(http_res, "default", CONTENT_TYPE_JSON):
            return unmarshal_json_response(models.DefaultError, http_res)

        raise errors.FastpixDefaultError(UNEXPECTED_RESPONSE_MESSAGE, http_res)
