"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from enum import Enum
from typing import Any, Iterator, Optional


def _coerce_attr(attr: Any) -> str:
    """Render a discriminator attribute value as a string."""
    if isinstance(attr, Enum):
        return f"{attr.value}"
    return f"{attr}"


def _get_field_discriminator(
    field: Any, fieldname: str, upper_fieldname: str, key: str
) -> Optional[str]:
    """Search for the discriminator attribute in a given field."""
    if isinstance(field, dict) and key in field:
        return f"{field[key]}"

    if hasattr(field, fieldname):
        return _coerce_attr(getattr(field, fieldname))

    if hasattr(field, upper_fieldname):
        return _coerce_attr(getattr(field, upper_fieldname))

    return None


def _child_objects(value: Any) -> Iterator[Any]:
    """Yield the nested sub-objects to recurse into for a mapping value."""
    if isinstance(value, list):
        yield from value
    elif isinstance(value, dict):
        yield value


def _search_nested_discriminator(
    obj: Any, fieldname: str, upper_fieldname: str, key: str
) -> Optional[str]:
    """Recursively search for the discriminator in nested structures."""
    discriminator = _get_field_discriminator(obj, fieldname, upper_fieldname, key)
    if discriminator is not None:
        return discriminator

    if isinstance(obj, dict):
        for value in obj.values():
            for child in _child_objects(value):
                nested = _search_nested_discriminator(
                    child, fieldname, upper_fieldname, key
                )
                if nested is not None:
                    return nested

    return None


def get_discriminator(model: Any, fieldname: str, key: str) -> str:
    """
    Recursively search for the discriminator attribute in a model.

    Args:
        model (Any): The model to search within.
        fieldname (str): The name of the field to search for.
        key (str): The key to search for in dictionaries.

    Returns:
        str: The name of the discriminator attribute.

    Raises:
        ValueError: If the discriminator attribute is not found.
    """
    upper_fieldname = fieldname.upper()

    if isinstance(model, list):
        for field in model:
            discriminator = _search_nested_discriminator(
                field, fieldname, upper_fieldname, key
            )
            if discriminator is not None:
                return discriminator

    discriminator = _search_nested_discriminator(
        model, fieldname, upper_fieldname, key
    )
    if discriminator is not None:
        return discriminator

    raise ValueError(f"Could not find discriminator field {fieldname} in {model}")
