"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

import re
import json
from typing import (
    Callable,
    Generic,
    TypeVar,
    Optional,
    Generator,
    AsyncGenerator,
    Tuple,
)
import httpx

T = TypeVar("T")


class EventStream(Generic[T]):
    # Holds a reference to the SDK client to avoid it being garbage collected
    # and cause termination of the underlying httpx client.
    client_ref: Optional[object]
    response: httpx.Response
    generator: Generator[T, None, None]

    def __init__(
        self,
        response: httpx.Response,
        decoder: Callable[[str], T],
        sentinel: Optional[str] = None,
        client_ref: Optional[object] = None,
    ):
        self.response = response
        self.generator = stream_events(response, decoder, sentinel)
        self.client_ref = client_ref

    def __iter__(self):
        return self

    def __next__(self):
        return next(self.generator)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.response.close()


class EventStreamAsync(Generic[T]):
    # Holds a reference to the SDK client to avoid it being garbage collected
    # and cause termination of the underlying httpx client.
    client_ref: Optional[object]
    response: httpx.Response
    generator: AsyncGenerator[T, None]

    def __init__(
        self,
        response: httpx.Response,
        decoder: Callable[[str], T],
        sentinel: Optional[str] = None,
        client_ref: Optional[object] = None,
    ):
        self.response = response
        self.generator = stream_events_async(response, decoder, sentinel)
        self.client_ref = client_ref

    def __aiter__(self):
        return self

    async def __anext__(self):
        return await self.generator.__anext__()

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.response.aclose()


class ServerEvent:
    id: Optional[str] = None
    event: Optional[str] = None
    data: Optional[str] = None
    retry: Optional[int] = None


MESSAGE_BOUNDARIES = [
    b"\r\n\r\n",
    b"\n\n",
    b"\r\r",
]


def _match_boundary(
    position: int, buffer: bytearray, char: bytes
) -> Optional[bytes]:
    """Return the message-boundary byte sequence at ``position``, else None."""
    if char not in (b"\r", b"\n"):
        return None
    for boundary in MESSAGE_BOUNDARIES:
        seq = _peek_sequence(position, buffer, boundary)
        if seq is not None:
            return seq
    return None


def _parse_sse_line(line: str) -> Optional[Tuple[str, str]]:
    """Split an SSE line into ``(field, value)``, or None when it should skip."""
    if not line:
        return None
    delim = line.find(":")
    if delim <= 0:
        return None
    field = line[0:delim]
    value = line[delim + 1 :] if delim < len(line) - 1 else ""
    if value and value[0] == " ":
        value = value[1:]
    return field, value


def _apply_sse_field(event: "ServerEvent", field: str, value: str) -> Optional[str]:
    """Apply one SSE field to ``event``.

    Returns the data fragment to append (``""`` for non-data fields), or None
    when the field is not a recognized SSE field.
    """
    if field == "event":
        event.event = value
        return ""
    if field == "data":
        return value + "\n"
    if field == "id":
        event.id = value
        return ""
    if field == "retry":
        event.retry = int(value) if value.isdigit() else None
        return ""
    return None


def _maybe_decode_json_data(data: str) -> object:
    """Return parsed JSON when ``data`` looks like JSON/a primitive, else raw."""
    looks_decodable = (
        data.isnumeric()
        or data in ("true", "false", "null")
        or data.startswith(("{", "[", '"'))
    )
    if looks_decodable:
        try:
            return json.loads(data)
        except Exception:
            pass
    return data


async def stream_events_async(
    response: httpx.Response,
    decoder: Callable[[str], T],
    sentinel: Optional[str] = None,
) -> AsyncGenerator[T, None]:
    buffer = bytearray()
    position = 0
    discard = False
    async for chunk in response.aiter_bytes():
        # We've encountered the sentinel value and should no longer process
        # incoming data. Instead we throw new data away until the server closes
        # the connection.
        if discard:
            continue

        buffer += chunk
        for i in range(position, len(buffer)):
            char = buffer[i : i + 1]
            seq = _match_boundary(i, buffer, char)
            if seq is None:
                continue

            block = buffer[position:i]
            position = i + len(seq)
            event, discard = _parse_event(block, decoder, sentinel)
            if event is not None:
                yield event

        if position > 0:
            buffer = buffer[position:]
            position = 0

    event, discard = _parse_event(buffer, decoder, sentinel)
    if event is not None:
        yield event


def stream_events(
    response: httpx.Response,
    decoder: Callable[[str], T],
    sentinel: Optional[str] = None,
) -> Generator[T, None, None]:
    buffer = bytearray()
    position = 0
    discard = False
    for chunk in response.iter_bytes():
        # We've encountered the sentinel value and should no longer process
        # incoming data. Instead we throw new data away until the server closes
        # the connection.
        if discard:
            continue

        buffer += chunk
        for i in range(position, len(buffer)):
            char = buffer[i : i + 1]
            seq = _match_boundary(i, buffer, char)
            if seq is None:
                continue

            block = buffer[position:i]
            position = i + len(seq)
            event, discard = _parse_event(block, decoder, sentinel)
            if event is not None:
                yield event

        if position > 0:
            buffer = buffer[position:]
            position = 0

    event, discard = _parse_event(buffer, decoder, sentinel)
    if event is not None:
        yield event


def _parse_event(
    raw: bytearray, decoder: Callable[[str], T], sentinel: Optional[str] = None
) -> Tuple[Optional[T], bool]:
    block = raw.decode()
    lines = re.split(r"\r?\n|\r", block)
    publish = False
    event = ServerEvent()
    data = ""
    for line in lines:
        parsed = _parse_sse_line(line)
        if parsed is None:
            continue
        field, value = parsed
        fragment = _apply_sse_field(event, field, value)
        if fragment is not None:
            publish = True
            data += fragment

    if sentinel and data == f"{sentinel}\n":
        return None, True

    if data:
        event.data = _maybe_decode_json_data(data[:-1])

    out = None
    if publish:
        out = decoder(json.dumps(event.__dict__))

    return out, False


def _peek_sequence(position: int, buffer: bytearray, sequence: bytes):
    if len(sequence) > (len(buffer) - position):
        return None

    for i, seq in enumerate(sequence):
        if buffer[position + i] != seq:
            return None

    return sequence
