"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from typing import (
    Any,
    Dict,
    List,
    Optional,
)
from httpx import Headers
from pydantic import BaseModel
from pydantic.fields import FieldInfo

from .metadata import (
    HeaderMetadata,
    find_field_metadata,
)

from .values import _is_set, _populate_from_globals, _val_to_string


def get_headers(headers_params: Any, gbls: Optional[Any] = None) -> Dict[str, str]:
    headers: Dict[str, str] = {}

    globals_already_populated = []
    if _is_set(headers_params):
        globals_already_populated = _populate_headers(headers_params, gbls, headers, [])
    if _is_set(gbls):
        _populate_headers(gbls, None, headers, globals_already_populated)

    return headers


def _populate_headers(
    headers_params: Any,
    gbls: Any,
    header_values: Dict[str, str],
    skip_fields: List[str],
) -> List[str]:
    globals_already_populated: List[str] = []

    if not isinstance(headers_params, BaseModel):
        return globals_already_populated

    param_fields: Dict[str, FieldInfo] = headers_params.__class__.model_fields
    for name in param_fields:
        if name in skip_fields:
            continue

        field = param_fields[name]
        f_name = field.alias if field.alias is not None else name

        metadata = find_field_metadata(field, HeaderMetadata)
        if metadata is None:
            continue

        value, global_found = _populate_from_globals(
            name, getattr(headers_params, name), HeaderMetadata, gbls
        )
        if global_found:
            globals_already_populated.append(name)
        value = _serialize_header(metadata.explode, value)

        if value != "":
            header_values[f_name] = value

    return globals_already_populated


def _serialize_header_basemodel(explode: bool, obj: BaseModel) -> str:
    items: List[str] = []
    obj_fields: Dict[str, FieldInfo] = obj.__class__.model_fields
    for name in obj_fields:
        obj_field = obj_fields[name]
        obj_param_metadata = find_field_metadata(obj_field, HeaderMetadata)

        if not obj_param_metadata:
            continue

        f_name = obj_field.alias if obj_field.alias is not None else name

        val = getattr(obj, name)
        if not _is_set(val):
            continue

        if explode:
            items.append(f"{f_name}={_val_to_string(val)}")
        else:
            items.append(f_name)
            items.append(_val_to_string(val))

    return ",".join(items)


def _serialize_header_dict(explode: bool, obj: Dict) -> str:
    items: List[str] = []
    for key, value in obj.items():
        if not _is_set(value):
            continue

        if explode:
            items.append(f"{key}={_val_to_string(value)}")
        else:
            items.append(key)
            items.append(_val_to_string(value))

    return ",".join(str(item) for item in items)


def _serialize_header_list(obj: List) -> str:
    items = [_val_to_string(value) for value in obj if _is_set(value)]
    return ",".join(items)


def _serialize_header(explode: bool, obj: Any) -> str:
    if not _is_set(obj):
        return ""

    if isinstance(obj, BaseModel):
        return _serialize_header_basemodel(explode, obj)
    if isinstance(obj, Dict):
        return _serialize_header_dict(explode, obj)
    if isinstance(obj, List):
        return _serialize_header_list(obj)
    return f"{_val_to_string(obj)}"


def get_response_headers(headers: Headers) -> Dict[str, List[str]]:
    res: Dict[str, List[str]] = {}
    for k, v in headers.items():
        if k not in res:
            res[k] = []

        res[k].append(v)
    return res
