"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


AudioTrackType = Literal["audio",]
r"""Defines the type of input track."""


class AudioTrackTypedDict(TypedDict):
    r"""A media consists of different media tracks, like video, audio, and subtitle, all combined."""

    id: NotRequired[str]
    r"""FastPix generates a unique identifier for each track."""
    type: NotRequired[AudioTrackType]
    r"""Defines the type of input track."""
    status: NotRequired[str]
    r"""Indicates the current state of the track. 'available' means the track has been processed successfully and is ready to be used or played."""
    language_name: NotRequired[str]
    r"""Name of the language in which the subtitles will be generated.

    """
    language_code: NotRequired[str]
    r"""Language codes are concise, standardized symbols that denote languages, utilizing either two or three characters for identification. The language code must be compliant with the BCP 47 standard to ensure compatibility. (for text only).

    """


class AudioTrack(BaseModel):
    r"""A media consists of different media tracks, like video, audio, and subtitle, all combined."""

    id: Optional[str] = None
    r"""FastPix generates a unique identifier for each track."""

    type: Optional[AudioTrackType] = None
    r"""Defines the type of input track."""

    status: Optional[str] = None
    r"""Indicates the current state of the track. 'available' means the track has been processed successfully and is ready to be used or played."""

    language_name: Annotated[Optional[str], pydantic.Field(alias="languageName")] = None
    r"""Name of the language in which the subtitles will be generated.

    """

    language_code: Annotated[Optional[str], pydantic.Field(alias="languageCode")] = None
    r"""Language codes are concise, standardized symbols that denote languages, utilizing either two or three characters for identification. The language code must be compliant with the BCP 47 standard to ensure compatibility. (for text only).

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "status", "languageName", "languageCode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
