"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BrowserNameDimensiondetailsTypedDict(TypedDict):
    value: NotRequired[str]
    r"""The specific metric value calculated based on the applied filters."""
    unique_count: NotRequired[int]
    r"""The count of unique viewers who interacted with the content."""
    count: NotRequired[int]
    r"""The count of viewers."""


class BrowserNameDimensiondetails(BaseModel):
    value: Optional[str] = None
    r"""The specific metric value calculated based on the applied filters."""

    unique_count: Annotated[Optional[int], pydantic.Field(alias="uniqueCount")] = None
    r"""The count of unique viewers who interacted with the content."""

    count: Optional[int] = None
    r"""The count of viewers."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["value", "uniqueCount", "count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
