"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from .livestreamresponsedto import LiveStreamResponseDTO, LiveStreamResponseDTOTypedDict
from typing import Union
from typing_extensions import TypeAliasType


CreateNewStreamResponseTypedDict = TypeAliasType(
    "CreateNewStreamResponseTypedDict",
    Union[LiveStreamResponseDTOTypedDict, DefaultErrorTypedDict],
)


CreateNewStreamResponse = TypeAliasType(
    "CreateNewStreamResponse", Union[LiveStreamResponseDTO, DefaultError]
)
