"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .basicaccesspolicy import BasicAccessPolicy
from .playbacksettings import PlaybackSettings, PlaybackSettingsTypedDict
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Dict, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


CreateLiveStreamRequestMaxResolution = Literal[
    "1080p",
    "720p",
    "480p",
]
r"""Defines the maximum resolution for encoding, storage, and playback of the live stream.

"""


class InputMediaSettingsTypedDict(TypedDict):
    r"""Contains configuration details for input media settings."""

    max_resolution: NotRequired[CreateLiveStreamRequestMaxResolution]
    r"""Defines the maximum resolution for encoding, storage, and playback of the live stream.

    """
    reconnect_window: NotRequired[int]
    r"""Time period (in seconds) FastPix waits to reconnect before ending the stream when disconnected.

    """
    media_policy: NotRequired[BasicAccessPolicy]
    r"""Basic access policy for media content"""
    metadata: NotRequired[Dict[str, str]]
    r"""Custom key–value pairs for tagging livestreams.
    Allows up to 10 entries with a maximum of 255 characters each.

    """
    enable_dvr_mode: NotRequired[bool]
    r"""Enables DVR (Digital Video Recorder) functionality, allowing viewers to pause, rewind, and resume live playback.

    """


class InputMediaSettings(BaseModel):
    r"""Contains configuration details for input media settings."""

    max_resolution: Annotated[
        Optional[CreateLiveStreamRequestMaxResolution],
        pydantic.Field(alias="maxResolution"),
    ] = "1080p"
    r"""Defines the maximum resolution for encoding, storage, and playback of the live stream.

    """

    reconnect_window: Annotated[
        Optional[int], pydantic.Field(alias="reconnectWindow")
    ] = 60
    r"""Time period (in seconds) FastPix waits to reconnect before ending the stream when disconnected.

    """

    media_policy: Annotated[
        Optional[BasicAccessPolicy], pydantic.Field(alias="mediaPolicy")
    ] = "public"
    r"""Basic access policy for media content"""

    metadata: Optional[Dict[str, str]] = None
    r"""Custom key–value pairs for tagging livestreams.
    Allows up to 10 entries with a maximum of 255 characters each.

    """

    enable_dvr_mode: Annotated[
        Optional[bool], pydantic.Field(alias="enableDvrMode")
    ] = None
    r"""Enables DVR (Digital Video Recorder) functionality, allowing viewers to pause, rewind, and resume live playback.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "maxResolution",
                "reconnectWindow",
                "mediaPolicy",
                "metadata",
                "enableDvrMode",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateLiveStreamRequestTypedDict(TypedDict):
    playback_settings: PlaybackSettingsTypedDict
    r"""Displays the result of the playback settings."""
    input_media_settings: InputMediaSettingsTypedDict
    r"""Contains configuration details for input media settings."""


class CreateLiveStreamRequest(BaseModel):
    playback_settings: Annotated[
        PlaybackSettings, pydantic.Field(alias="playbackSettings")
    ]
    r"""Displays the result of the playback settings."""

    input_media_settings: Annotated[
        InputMediaSettings, pydantic.Field(alias="inputMediaSettings")
    ]
    r"""Contains configuration details for input media settings."""
