"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .createplaylistrequestmanual import (
    CreatePlaylistRequestManual,
    CreatePlaylistRequestManualTypedDict,
)
from .createplaylistrequestsmart import (
    CreatePlaylistRequestSmart,
    CreatePlaylistRequestSmartTypedDict,
)
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType


CreatePlaylistRequestTypedDict = TypeAliasType(
    "CreatePlaylistRequestTypedDict",
    Union[CreatePlaylistRequestManualTypedDict, CreatePlaylistRequestSmartTypedDict],
)


CreatePlaylistRequest = Annotated[
    Union[CreatePlaylistRequestManual, CreatePlaylistRequestSmart],
    Field(discriminator="type"),
]
