"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from .livestreamdeleteresponse import (
    LiveStreamDeleteResponse,
    LiveStreamDeleteResponseTypedDict,
)
from fastpix_python.types import BaseModel
from fastpix_python.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class DeletePlaybackIDOfStreamRequestTypedDict(TypedDict):
    stream_id: str
    r"""Upon creating a new live stream, FastPix assigns a unique identifier to the stream."""
    playback_id: str
    r"""Unique identifier for the playbackId"""


class DeletePlaybackIDOfStreamRequest(BaseModel):
    stream_id: Annotated[
        str,
        pydantic.Field(alias="streamId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Upon creating a new live stream, FastPix assigns a unique identifier to the stream."""

    playback_id: Annotated[
        str,
        pydantic.Field(alias="playbackId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Unique identifier for the playbackId"""


DeletePlaybackIDOfStreamResponseTypedDict = TypeAliasType(
    "DeletePlaybackIDOfStreamResponseTypedDict",
    Union[LiveStreamDeleteResponseTypedDict, DefaultErrorTypedDict],
)


DeletePlaybackIDOfStreamResponse = TypeAliasType(
    "DeletePlaybackIDOfStreamResponse", Union[LiveStreamDeleteResponse, DefaultError]
)
