"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from .deletesigningkeyresponse import (
    DeleteSigningKeyResponse,
    DeleteSigningKeyResponseTypedDict,
)
from fastpix_python.types import BaseModel
from fastpix_python.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class DeleteSigningKeyRequestTypedDict(TypedDict):
    signing_key_id: str
    r"""When creating the signing key, FastPix assigns a universally unique identifier with a maximum length of 255 characters."""


class DeleteSigningKeyRequest(BaseModel):
    signing_key_id: Annotated[
        str,
        pydantic.Field(alias="signingKeyId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""When creating the signing key, FastPix assigns a universally unique identifier with a maximum length of 255 characters."""


DeleteSigningKeyResponseResponseTypedDict = TypeAliasType(
    "DeleteSigningKeyResponseResponseTypedDict",
    Union[DeleteSigningKeyResponseTypedDict, DefaultErrorTypedDict],
)


DeleteSigningKeyResponseResponse = TypeAliasType(
    "DeleteSigningKeyResponseResponse", Union[DeleteSigningKeyResponse, DefaultError]
)
