"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from .getmediaresponse import GetMediaResponse, GetMediaResponseTypedDict
from fastpix_python.types import BaseModel, UNSET_SENTINEL
from fastpix_python.utils import FieldMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GetMediaRequestTypedDict(TypedDict):
    media_id: str
    r"""The unique identifier assigned to the media when created. The value must be a valid UUID."""


class GetMediaRequest(BaseModel):
    media_id: Annotated[
        str,
        pydantic.Field(alias="mediaId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier assigned to the media when created. The value must be a valid UUID."""


class GetMediaResponseBodyTypedDict(TypedDict):
    r"""Get a video media by id"""

    success: NotRequired[bool]
    r"""Demonstrates whether the request is successful or not."""
    data: NotRequired[GetMediaResponseTypedDict]


class GetMediaResponseBody(BaseModel):
    r"""Get a video media by id"""

    success: Optional[bool] = None
    r"""Demonstrates whether the request is successful or not."""

    data: Optional[GetMediaResponse] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GetMediaResponseResponseTypedDict = TypeAliasType(
    "GetMediaResponseResponseTypedDict",
    Union[GetMediaResponseBodyTypedDict, DefaultErrorTypedDict],
)


GetMediaResponseResponse = TypeAliasType(
    "GetMediaResponseResponse", Union[GetMediaResponseBody, DefaultError]
)
