"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from .getstreamsresponse import GetStreamsResponse, GetStreamsResponseTypedDict
from fastpix_python.types import BaseModel, UNSET_SENTINEL
from fastpix_python.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


OrderBy = Literal[
    "asc",
    "desc",
]
r"""The list of value can be order in two ways DESC (Descending) or ASC (Ascending). In case not specified, by default it will be DESC."""


class GetAllStreamsRequestTypedDict(TypedDict):
    limit: NotRequired[int]
    r"""Limit specifies the maximum number of items to display per page."""
    offset: NotRequired[int]
    r"""Offset determines the starting point for data retrieval within a paginated list."""
    order_by: NotRequired[OrderBy]
    r"""The list of value can be order in two ways DESC (Descending) or ASC (Ascending). In case not specified, by default it will be DESC."""


class GetAllStreamsRequest(BaseModel):
    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10
    r"""Limit specifies the maximum number of items to display per page."""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Offset determines the starting point for data retrieval within a paginated list."""

    order_by: Annotated[
        Optional[OrderBy],
        pydantic.Field(alias="orderBy"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "desc"
    r"""The list of value can be order in two ways DESC (Descending) or ASC (Ascending). In case not specified, by default it will be DESC."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["limit", "offset", "orderBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GetAllStreamsResponseTypedDict = TypeAliasType(
    "GetAllStreamsResponseTypedDict",
    Union[DefaultErrorTypedDict, GetStreamsResponseTypedDict],
)


GetAllStreamsResponse = TypeAliasType(
    "GetAllStreamsResponse", Union[DefaultError, GetStreamsResponse]
)
