"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from .views import Views, ViewsTypedDict
from fastpix_python.types import BaseModel, UNSET_SENTINEL
from fastpix_python.utils import FieldMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GetVideoViewDetailsRequestTypedDict(TypedDict):
    view_id: str
    r"""Pass View Id"""


class GetVideoViewDetailsRequest(BaseModel):
    view_id: Annotated[
        str,
        pydantic.Field(alias="viewId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Pass View Id"""


class GetVideoViewDetailsResponseBodyTypedDict(TypedDict):
    r"""Get a video view by id"""

    success: NotRequired[bool]
    r"""Shows the request status. Returns true for success and false for failure."""
    data: NotRequired[ViewsTypedDict]
    r"""Displays the result of the request."""


class GetVideoViewDetailsResponseBody(BaseModel):
    r"""Get a video view by id"""

    success: Optional[bool] = None
    r"""Shows the request status. Returns true for success and false for failure."""

    data: Optional[Views] = None
    r"""Displays the result of the request."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GetVideoViewDetailsResponseTypedDict = TypeAliasType(
    "GetVideoViewDetailsResponseTypedDict",
    Union[GetVideoViewDetailsResponseBodyTypedDict, DefaultErrorTypedDict],
)


GetVideoViewDetailsResponse = TypeAliasType(
    "GetVideoViewDetailsResponse", Union[GetVideoViewDetailsResponseBody, DefaultError]
)
