"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from datetime import datetime
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetAllSigningKeysResponseDtoTypedDict(TypedDict):
    r"""Displays the result of the request."""

    id: NotRequired[str]
    r"""A unique identifier is generated by FastPix for the signing keys."""
    created_at: NotRequired[datetime]
    r"""Time the Signing key was generated, defined as a localDateTime (UTC Time)."""


class GetAllSigningKeysResponseDto(BaseModel):
    r"""Displays the result of the request."""

    id: Optional[str] = None
    r"""A unique identifier is generated by FastPix for the signing keys."""

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None
    r"""Time the Signing key was generated, defined as a localDateTime (UTC Time)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "createdAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
