"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from .drmidresponse import DrmIDResponse, DrmIDResponseTypedDict
from .pagination import Pagination, PaginationTypedDict
from fastpix_python.types import BaseModel, UNSET_SENTINEL
from fastpix_python.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GetDrmConfigurationRequestTypedDict(TypedDict):
    offset: NotRequired[int]
    r"""Offset determines the starting point for data retrieval within a paginated list."""
    limit: NotRequired[int]
    r"""Limit specifies the maximum number of items to display per page."""


class GetDrmConfigurationRequest(BaseModel):
    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Offset determines the starting point for data retrieval within a paginated list."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10
    r"""Limit specifies the maximum number of items to display per page."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["offset", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetDrmConfigurationResponseBodyTypedDict(TypedDict):
    r"""DRM configuration(s) retrieved successfully"""

    success: NotRequired[bool]
    r"""Shows the request status. Returns true for success and false for failure."""
    data: NotRequired[List[DrmIDResponseTypedDict]]
    pagination: NotRequired[PaginationTypedDict]
    r"""Pagination organizes content into pages for better readability and navigation."""


class GetDrmConfigurationResponseBody(BaseModel):
    r"""DRM configuration(s) retrieved successfully"""

    success: Optional[bool] = None
    r"""Shows the request status. Returns true for success and false for failure."""

    data: Optional[List[DrmIDResponse]] = None

    pagination: Optional[Pagination] = None
    r"""Pagination organizes content into pages for better readability and navigation."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data", "pagination"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GetDrmConfigurationResponseTypedDict = TypeAliasType(
    "GetDrmConfigurationResponseTypedDict",
    Union[DefaultErrorTypedDict, GetDrmConfigurationResponseBodyTypedDict],
)


GetDrmConfigurationResponse = TypeAliasType(
    "GetDrmConfigurationResponse", Union[DefaultError, GetDrmConfigurationResponseBody]
)
