"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from .live_media_clips import LiveMediaClips, LiveMediaClipsTypedDict
from .pagination import Pagination, PaginationTypedDict
from .sortorder import SortOrder
from fastpix_python.types import BaseModel, UNSET_SENTINEL
from fastpix_python.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class ListLiveClipsRequestTypedDict(TypedDict):
    livestream_id: str
    r"""The stream Id is unique identifier assigned to the live stream."""
    limit: NotRequired[int]
    r"""Limit specifies the maximum number of items to display per page."""
    offset: NotRequired[int]
    r"""Offset determines the starting point for data retrieval within a paginated list."""
    order_by: NotRequired[SortOrder]
    r"""The values in the list can be arranged in two ways: DESC (Descending) or ASC (Ascending)."""


class ListLiveClipsRequest(BaseModel):
    livestream_id: Annotated[
        str,
        pydantic.Field(alias="livestreamId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The stream Id is unique identifier assigned to the live stream."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10
    r"""Limit specifies the maximum number of items to display per page."""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Offset determines the starting point for data retrieval within a paginated list."""

    order_by: Annotated[
        Optional[SortOrder],
        pydantic.Field(alias="orderBy"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "desc"
    r"""The values in the list can be arranged in two ways: DESC (Descending) or ASC (Ascending)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["limit", "offset", "orderBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListLiveClipsResponseBodyTypedDict(TypedDict):
    r"""List of video media"""

    success: NotRequired[bool]
    r"""Demonstrates whether the request is successful or not."""
    data: NotRequired[List[LiveMediaClipsTypedDict]]
    r"""Displays the result of the request."""
    pagination: NotRequired[PaginationTypedDict]
    r"""Pagination organizes content into pages for better readability and navigation."""


class ListLiveClipsResponseBody(BaseModel):
    r"""List of video media"""

    success: Optional[bool] = None
    r"""Demonstrates whether the request is successful or not."""

    data: Optional[List[LiveMediaClips]] = None
    r"""Displays the result of the request."""

    pagination: Optional[Pagination] = None
    r"""Pagination organizes content into pages for better readability and navigation."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data", "pagination"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListLiveClipsResponseTypedDict = TypeAliasType(
    "ListLiveClipsResponseTypedDict",
    Union[DefaultErrorTypedDict, ListLiveClipsResponseBodyTypedDict],
)


ListLiveClipsResponse = TypeAliasType(
    "ListLiveClipsResponse", Union[DefaultError, ListLiveClipsResponseBody]
)
