"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from .errordetails import ErrorDetails, ErrorDetailsTypedDict
from .toperrordetails import TopErrorDetails, TopErrorDetailsTypedDict
from fastpix_python.types import BaseModel, UNSET_SENTINEL
from fastpix_python.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


ListErrorsTimespan = Literal[
    "60:minutes",
    "6:hours",
    "24:hours",
    "3:days",
    "7:days",
    "30:days",
]
r"""This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.

**Accepted formats are:**

array of epoch timestamps for example
`timespan[]=1498867200&timespan[]=1498953600`

duration string for example
`timespan[]=24:hours` or `timespan[]=7:days`

"""


class ListErrorsRequestTypedDict(TypedDict):
    timespan: NotRequired[ListErrorsTimespan]
    r"""This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.

    **Accepted formats are:**

    array of epoch timestamps for example
    `timespan[]=1498867200&timespan[]=1498953600`

    duration string for example
    `timespan[]=24:hours` or `timespan[]=7:days`

    """
    filterby: NotRequired[str]
    r"""Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass \"!\" before the filter value. The list of filters can be obtained from list of dimensions endpoint.
    Example Values : [ browser_name:Chrome , os_name:macOS , !device_name:Galaxy ]

    """
    limit: NotRequired[int]
    r"""Pass the limit to display only the rows specified by the value for top errors.

    """


class ListErrorsRequest(BaseModel):
    timespan: Annotated[
        Optional[ListErrorsTimespan],
        pydantic.Field(alias="timespan[]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.

    **Accepted formats are:**

    array of epoch timestamps for example
    `timespan[]=1498867200&timespan[]=1498953600`

    duration string for example
    `timespan[]=24:hours` or `timespan[]=7:days`

    """

    filterby: Annotated[
        Optional[str],
        pydantic.Field(alias="filterby[]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass \"!\" before the filter value. The list of filters can be obtained from list of dimensions endpoint.
    Example Values : [ browser_name:Chrome , os_name:macOS , !device_name:Galaxy ]

    """

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Pass the limit to display only the rows specified by the value for top errors.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["timespan[]", "filterby[]", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListErrorsDataTypedDict(TypedDict):
    r"""Displays the result of the request."""

    errors: NotRequired[List[ErrorDetailsTypedDict]]
    r"""The endpoint retrieves a comprehensive list of errors that have occurred by providing detailed information about each error instance."""
    top_errors: NotRequired[List[TopErrorDetailsTypedDict]]
    r"""Retrieves a list of errors that have occurred most frequently in the system, ranked by their count of occurrences."""


class ListErrorsData(BaseModel):
    r"""Displays the result of the request."""

    errors: Optional[List[ErrorDetails]] = None
    r"""The endpoint retrieves a comprehensive list of errors that have occurred by providing detailed information about each error instance."""

    top_errors: Annotated[
        Optional[List[TopErrorDetails]], pydantic.Field(alias="topErrors")
    ] = None
    r"""Retrieves a list of errors that have occurred most frequently in the system, ranked by their count of occurrences."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["errors", "topErrors"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListErrorsResponseBodyTypedDict(TypedDict):
    r"""Get filter/ dimension value details by dimension name."""

    success: NotRequired[bool]
    r"""Shows the request status. Returns true for success and false for failure."""
    data: NotRequired[ListErrorsDataTypedDict]
    r"""Displays the result of the request."""
    timespan: NotRequired[List[int]]
    r"""The timespan from and to details displayed in the form of unix epoch timestamps.

    """


class ListErrorsResponseBody(BaseModel):
    r"""Get filter/ dimension value details by dimension name."""

    success: Optional[bool] = None
    r"""Shows the request status. Returns true for success and false for failure."""

    data: Optional[ListErrorsData] = None
    r"""Displays the result of the request."""

    timespan: Optional[List[int]] = None
    r"""The timespan from and to details displayed in the form of unix epoch timestamps.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data", "timespan"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListErrorsResponseTypedDict = TypeAliasType(
    "ListErrorsResponseTypedDict",
    Union[DefaultErrorTypedDict, ListErrorsResponseBodyTypedDict],
)


ListErrorsResponse = TypeAliasType(
    "ListErrorsResponse", Union[DefaultError, ListErrorsResponseBody]
)
