"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .datapagination import DataPagination, DataPaginationTypedDict
from .default_error import DefaultError, DefaultErrorTypedDict
from .metricsbreakdowndetails import (
    MetricsBreakdownDetails,
    MetricsBreakdownDetailsTypedDict,
)
from .metricsmetadatadetails import (
    MetricsmetadataDetails,
    MetricsmetadataDetailsTypedDict,
)
from fastpix_python.types import BaseModel, UNSET_SENTINEL
from fastpix_python.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


ListBreakdownValuesMetricID = Literal[
    "views",
    "unique_viewers",
    "playing_time",
    "quality_of_experience_score",
    "playback_score",
    "playback_failure_percentage",
    "exit_before_video_start",
    "video_startup_failure_percentage",
    "startup_score",
    "video_startup_time",
    "player_startup_time",
    "page_load_time",
    "total_startup_time",
    "live_stream_latency",
    "average_bitrate",
    "buffer_count",
    "render_quality_score",
    "avg_upscaling",
    "avg_downscaling",
    "max_upscaling",
    "max_downscaling",
    "jump_latency",
    "stability_score",
    "buffer_ratio",
    "buffer_frequency",
    "buffer_fill",
]
r"""Pass metric Id

"""


ListBreakdownValuesTimespan = Literal[
    "60:minutes",
    "6:hours",
    "24:hours",
    "3:days",
    "7:days",
    "30:days",
]
r"""This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.

**Accepted formats are:**

array of epoch timestamps for example
`timespan[]=1498867200&timespan[]=1498953600`

duration string for example
`timespan[]=24:hours` or `timespan[]=7:days`

"""


ListBreakdownValuesSortOrder = Literal[
    "asc",
    "desc",
]
r"""The order direction to sort the metrics list by.

"""


class ListBreakdownValuesRequestTypedDict(TypedDict):
    metric_id: ListBreakdownValuesMetricID
    r"""Pass metric Id

    """
    timespan: NotRequired[ListBreakdownValuesTimespan]
    r"""This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.

    **Accepted formats are:**

    array of epoch timestamps for example
    `timespan[]=1498867200&timespan[]=1498953600`

    duration string for example
    `timespan[]=24:hours` or `timespan[]=7:days`

    """
    filterby: NotRequired[str]
    r"""Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass \"!\" before the filter value. The list of filters can be obtained from list of dimensions endpoint.
    Example Values : [ browser_name:Chrome , os_name:macOS , !device_name:Galaxy ]

    """
    limit: NotRequired[int]
    r"""Pass the limit to display only the rows specified by the value.

    """
    offset: NotRequired[int]
    r"""Pass the offset value to indicate the page number.

    """
    group_by: NotRequired[str]
    r"""Pass this value to group the metrics list by.
    Possible Values : [\"browser_name\", \"browser_version\", \"os_name\",\"os_version\" , \"device_name\", \"device_model\", \"device_type\", \"device_manufacturer\", \"player_remote_played\",player_name\", \"player_version\", \"player_software_name\", \"player_software_version\", \"player_resolution\", \"fp_sdk\",\"fp_sdk_version\", \"player_autoplay_on\", \"player_preload_on\",\"video_title\",  \"video_id\", \"video_series\" ,  \"fp_playback_id\",\"fp_live_stream_id\", \"media_id\",\"video_source_stream_type\", \"video_source_type\", \"video_encoding_variant\", \"experiment_name\", \"sub_property_id\", \"drm_type\",\"asn_name\", \"cdn\", \"video_source_hostname\", \"connection_type\", \"view_session_id\",\"continent\",\"country\", \"region\",\"viewer_id\", \"error_code\", \"exit_before_video_start\", \"view_has_ad\", \"video_startup_failed\" , \"page_context\", \"playback_failed\".]

    """
    order_by: NotRequired[str]
    r"""Pass this value to order the metrics list by.

    """
    sort_order: NotRequired[ListBreakdownValuesSortOrder]
    r"""The order direction to sort the metrics list by.

    """
    measurement: NotRequired[str]
    r"""The measurement for the given metrics.
    Possible Values : [95th, median, avg, count or sum]

    """


class ListBreakdownValuesRequest(BaseModel):
    metric_id: Annotated[
        ListBreakdownValuesMetricID,
        pydantic.Field(alias="metricId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Pass metric Id

    """

    timespan: Annotated[
        Optional[ListBreakdownValuesTimespan],
        pydantic.Field(alias="timespan[]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.

    **Accepted formats are:**

    array of epoch timestamps for example
    `timespan[]=1498867200&timespan[]=1498953600`

    duration string for example
    `timespan[]=24:hours` or `timespan[]=7:days`

    """

    filterby: Annotated[
        Optional[str],
        pydantic.Field(alias="filterby[]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass \"!\" before the filter value. The list of filters can be obtained from list of dimensions endpoint.
    Example Values : [ browser_name:Chrome , os_name:macOS , !device_name:Galaxy ]

    """

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10
    r"""Pass the limit to display only the rows specified by the value.

    """

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Pass the offset value to indicate the page number.

    """

    group_by: Annotated[
        Optional[str],
        pydantic.Field(alias="groupBy"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pass this value to group the metrics list by.
    Possible Values : [\"browser_name\", \"browser_version\", \"os_name\",\"os_version\" , \"device_name\", \"device_model\", \"device_type\", \"device_manufacturer\", \"player_remote_played\",player_name\", \"player_version\", \"player_software_name\", \"player_software_version\", \"player_resolution\", \"fp_sdk\",\"fp_sdk_version\", \"player_autoplay_on\", \"player_preload_on\",\"video_title\",  \"video_id\", \"video_series\" ,  \"fp_playback_id\",\"fp_live_stream_id\", \"media_id\",\"video_source_stream_type\", \"video_source_type\", \"video_encoding_variant\", \"experiment_name\", \"sub_property_id\", \"drm_type\",\"asn_name\", \"cdn\", \"video_source_hostname\", \"connection_type\", \"view_session_id\",\"continent\",\"country\", \"region\",\"viewer_id\", \"error_code\", \"exit_before_video_start\", \"view_has_ad\", \"video_startup_failed\" , \"page_context\", \"playback_failed\".]

    """

    order_by: Annotated[
        Optional[str],
        pydantic.Field(alias="orderBy"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "views"
    r"""Pass this value to order the metrics list by.

    """

    sort_order: Annotated[
        Optional[ListBreakdownValuesSortOrder],
        pydantic.Field(alias="sortOrder"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "asc"
    r"""The order direction to sort the metrics list by.

    """

    measurement: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "avg"
    r"""The measurement for the given metrics.
    Possible Values : [95th, median, avg, count or sum]

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "timespan[]",
                "filterby[]",
                "limit",
                "offset",
                "groupBy",
                "orderBy",
                "sortOrder",
                "measurement",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListBreakdownValuesResponseBodyTypedDict(TypedDict):
    r"""Get filter/ dimension value details by dimension name."""

    success: NotRequired[bool]
    r"""Shows the request status. Returns true for success and false for failure."""
    metadata: NotRequired[MetricsmetadataDetailsTypedDict]
    r"""Retrieves breakdown values for a specified metric and timespan"""
    data: NotRequired[List[MetricsBreakdownDetailsTypedDict]]
    r"""Retrieves breakdown values for a specified metric and timespan"""
    pagination: NotRequired[DataPaginationTypedDict]
    r"""Pagination organizes content into pages for better readability and navigation."""
    timespan: NotRequired[List[int]]
    r"""The timespan from and to details displayed in the form of unix epoch timestamps.

    """


class ListBreakdownValuesResponseBody(BaseModel):
    r"""Get filter/ dimension value details by dimension name."""

    success: Optional[bool] = None
    r"""Shows the request status. Returns true for success and false for failure."""

    metadata: Optional[MetricsmetadataDetails] = None
    r"""Retrieves breakdown values for a specified metric and timespan"""

    data: Optional[List[MetricsBreakdownDetails]] = None
    r"""Retrieves breakdown values for a specified metric and timespan"""

    pagination: Optional[DataPagination] = None
    r"""Pagination organizes content into pages for better readability and navigation."""

    timespan: Optional[List[int]] = None
    r"""The timespan from and to details displayed in the form of unix epoch timestamps.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "metadata", "data", "pagination", "timespan"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListBreakdownValuesResponseTypedDict = TypeAliasType(
    "ListBreakdownValuesResponseTypedDict",
    Union[DefaultErrorTypedDict, ListBreakdownValuesResponseBodyTypedDict],
)


ListBreakdownValuesResponse = TypeAliasType(
    "ListBreakdownValuesResponse", Union[DefaultError, ListBreakdownValuesResponseBody]
)
