"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class LiveStreamPaginationTypedDict(TypedDict):
    r"""Pagination organizes content into pages for better readability and navigation."""

    total_records: NotRequired[int]
    r"""It gives the total number of media assets that are accessible overall."""
    current_offset: NotRequired[int]
    r"""Determines the current point for data retrieval within a paginated list."""
    offset_count: NotRequired[int]
    r"""The offset count is expressed as total records by limit."""


class LiveStreamPagination(BaseModel):
    r"""Pagination organizes content into pages for better readability and navigation."""

    total_records: Annotated[Optional[int], pydantic.Field(alias="totalRecords")] = None
    r"""It gives the total number of media assets that are accessible overall."""

    current_offset: Annotated[Optional[int], pydantic.Field(alias="currentOffset")] = (
        None
    )
    r"""Determines the current point for data retrieval within a paginated list."""

    offset_count: Annotated[Optional[int], pydantic.Field(alias="offsetCount")] = None
    r"""The offset count is expressed as total records by limit."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["totalRecords", "currentOffset", "offsetCount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
