"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .audiotrack import AudioTrack, AudioTrackTypedDict
from .playbackid import PlaybackID, PlaybackIDTypedDict
from .subtitletrack import SubtitleTrack, SubtitleTrackTypedDict
from .trackssubtitles import TracksSubtitles, TracksSubtitlesTypedDict
from .videotrack import VideoTrack, VideoTrackTypedDict
from datetime import datetime
from fastpix_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


LiveMediaClipsMaxResolution = Literal[
    "2160p",
    "1440p",
    "1080p",
    "720p",
    "480p",
]
r"""The maximum resolution specified by the user for the media."""


LiveMediaClipsSourceResolution = Literal[
    "2160p",
    "2160",
    "1440p",
    "1440",
    "1080p",
    "1080",
    "720p",
    "720",
    "480p",
    "480",
]
r"""The actual resolution of the uploaded media. This represents the native quality of the source media."""


LiveMediaClipsStatus = Literal[
    "Created",
    "Downloading",
    "Downloaded",
    "Validating",
    "In Queue",
    "Processing",
    "Ready",
    "Failed",
]
r"""Determines the media's status, which can be one of the possible values."""


LiveMediaClipsTrackTypedDict = TypeAliasType(
    "LiveMediaClipsTrackTypedDict",
    Union[AudioTrackTypedDict, SubtitleTrackTypedDict, VideoTrackTypedDict],
)


LiveMediaClipsTrack = TypeAliasType(
    "LiveMediaClipsTrack", Union[AudioTrack, SubtitleTrack, VideoTrack]
)


LiveMediaClipsMp4Support = Literal[
    "none",
    "capped_4k",
    "audioOnly",
    "audioOnly,capped_4k",
]
r"""Determines the type of MP4 support for the media.
- **none**: Disables MP4 support.
- **capped_4k**: Enables MP4 downloads with resolutions up to 4K.
- **audioOnly**: Provides an MP4 stream containing only the audio.
- **audioOnly,capped_4k**: Enables both MP4 video downloads (up to 4K) and an audio-only stream.

"""


class LiveMediaClipsTypedDict(TypedDict):
    thumbnail: NotRequired[Nullable[str]]
    r"""A video thumbnail is a still image that acts as the preview image for your video."""
    id: NotRequired[str]
    r"""The unique identifier assigned to the media when created. The value must be a valid UUID."""
    workspace_id: NotRequired[str]
    r"""A unique identifier is generated by FastPix for the workspace."""
    stream_id: NotRequired[str]
    r"""The ID of the livestream for which the clips were created."""
    creator_id: NotRequired[str]
    r"""The unique identifier of the user who created this media."""
    title: NotRequired[Nullable[str]]
    r"""Title of the media file."""
    max_resolution: NotRequired[LiveMediaClipsMaxResolution]
    r"""The maximum resolution specified by the user for the media."""
    source_resolution: NotRequired[LiveMediaClipsSourceResolution]
    r"""The actual resolution of the uploaded media. This represents the native quality of the source media."""
    status: NotRequired[LiveMediaClipsStatus]
    r"""Determines the media's status, which can be one of the possible values."""
    source_access: NotRequired[bool]
    r"""The sourceAccess parameter determines whether the original media file is accessible. Set to true to enable access or false to restrict it."""
    playback_ids: NotRequired[List[PlaybackIDTypedDict]]
    r"""A collection of Playback ID objects utilized for crafting HLS playback URLs."""
    tracks: NotRequired[List[LiveMediaClipsTrackTypedDict]]
    r"""A media consists of different media tracks, like video, audio, and subtitle, all combined."""
    mp4_support: NotRequired[LiveMediaClipsMp4Support]
    r"""Determines the type of MP4 support for the media.
    - **none**: Disables MP4 support.
    - **capped_4k**: Enables MP4 downloads with resolutions up to 4K.
    - **audioOnly**: Provides an MP4 stream containing only the audio.
    - **audioOnly,capped_4k**: Enables both MP4 video downloads (up to 4K) and an audio-only stream.

    """
    generated_subtitles: NotRequired[Nullable[List[TracksSubtitlesTypedDict]]]
    r"""List of generated subtitle tracks associated with the media."""
    is_audio_only: NotRequired[Nullable[bool]]
    r"""Indicates whether the media contains only audio (no video track)."""
    subtitle_available: NotRequired[Nullable[bool]]
    r"""Indicates whether subtitles are available for the media."""
    duration: NotRequired[str]
    r"""The length of the media in seconds, with a maximum allowed duration of 12 hours per individual media."""
    aspect_ratio: NotRequired[Nullable[str]]
    r"""The aspect ratio of a video is a value that describes the relative shape of a video based on its width and height."""
    created_at: NotRequired[datetime]
    r"""Time the media was created, defined as a localDateTime (UTC Time)."""
    updated_at: NotRequired[datetime]
    r"""Time the media was updated, defined as a localDateTime (UTC Time)."""


class LiveMediaClips(BaseModel):
    thumbnail: OptionalNullable[str] = UNSET
    r"""A video thumbnail is a still image that acts as the preview image for your video."""

    id: Optional[str] = None
    r"""The unique identifier assigned to the media when created. The value must be a valid UUID."""

    workspace_id: Annotated[Optional[str], pydantic.Field(alias="workspaceId")] = None
    r"""A unique identifier is generated by FastPix for the workspace."""

    stream_id: Annotated[Optional[str], pydantic.Field(alias="streamId")] = None
    r"""The ID of the livestream for which the clips were created."""

    creator_id: Annotated[Optional[str], pydantic.Field(alias="creatorId")] = None
    r"""The unique identifier of the user who created this media."""

    title: OptionalNullable[str] = UNSET
    r"""Title of the media file."""

    max_resolution: Annotated[
        Optional[LiveMediaClipsMaxResolution], pydantic.Field(alias="maxResolution")
    ] = "1080p"
    r"""The maximum resolution specified by the user for the media."""

    source_resolution: Annotated[
        Optional[LiveMediaClipsSourceResolution],
        pydantic.Field(alias="sourceResolution"),
    ] = "1080p"
    r"""The actual resolution of the uploaded media. This represents the native quality of the source media."""

    status: Optional[LiveMediaClipsStatus] = None
    r"""Determines the media's status, which can be one of the possible values."""

    source_access: Annotated[Optional[bool], pydantic.Field(alias="sourceAccess")] = (
        None
    )
    r"""The sourceAccess parameter determines whether the original media file is accessible. Set to true to enable access or false to restrict it."""

    playback_ids: Annotated[
        Optional[List[PlaybackID]], pydantic.Field(alias="playbackIds")
    ] = None
    r"""A collection of Playback ID objects utilized for crafting HLS playback URLs."""

    tracks: Optional[List[LiveMediaClipsTrack]] = None
    r"""A media consists of different media tracks, like video, audio, and subtitle, all combined."""

    mp4_support: Annotated[
        Optional[LiveMediaClipsMp4Support], pydantic.Field(alias="mp4Support")
    ] = None
    r"""Determines the type of MP4 support for the media.
    - **none**: Disables MP4 support.
    - **capped_4k**: Enables MP4 downloads with resolutions up to 4K.
    - **audioOnly**: Provides an MP4 stream containing only the audio.
    - **audioOnly,capped_4k**: Enables both MP4 video downloads (up to 4K) and an audio-only stream.

    """

    generated_subtitles: Annotated[
        OptionalNullable[List[TracksSubtitles]],
        pydantic.Field(alias="generatedSubtitles"),
    ] = UNSET
    r"""List of generated subtitle tracks associated with the media."""

    is_audio_only: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="isAudioOnly")
    ] = UNSET
    r"""Indicates whether the media contains only audio (no video track)."""

    subtitle_available: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="subtitleAvailable")
    ] = UNSET
    r"""Indicates whether subtitles are available for the media."""

    duration: Optional[str] = None
    r"""The length of the media in seconds, with a maximum allowed duration of 12 hours per individual media."""

    aspect_ratio: Annotated[
        OptionalNullable[str], pydantic.Field(alias="aspectRatio")
    ] = UNSET
    r"""The aspect ratio of a video is a value that describes the relative shape of a video based on its width and height."""

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None
    r"""Time the media was created, defined as a localDateTime (UTC Time)."""

    updated_at: Annotated[Optional[datetime], pydantic.Field(alias="updatedAt")] = None
    r"""Time the media was updated, defined as a localDateTime (UTC Time)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "thumbnail",
                "id",
                "workspaceId",
                "streamId",
                "creatorId",
                "title",
                "maxResolution",
                "sourceResolution",
                "status",
                "sourceAccess",
                "playbackIds",
                "tracks",
                "mp4Support",
                "generatedSubtitles",
                "isAudioOnly",
                "subtitleAvailable",
                "duration",
                "aspectRatio",
                "createdAt",
                "updatedAt",
            ]
        )
        nullable_fields = set(
            [
                "thumbnail",
                "title",
                "generatedSubtitles",
                "isAudioOnly",
                "subtitleAvailable",
                "aspectRatio",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
