"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .getcreatelivestreamresponsedto import (
    GetCreateLiveStreamResponseDTO,
    GetCreateLiveStreamResponseDTOTypedDict,
)
from fastpix_python.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class LivestreamgetResponseTypedDict(TypedDict):
    r"""Displays the result of the request."""

    success: NotRequired[bool]
    r"""Shows the request status. Returns true for success and false for failure."""
    data: NotRequired[GetCreateLiveStreamResponseDTOTypedDict]
    r"""Displays the result of the request."""


class LivestreamgetResponse(BaseModel):
    r"""Displays the result of the request."""

    success: Optional[bool] = None
    r"""Shows the request status. Returns true for success and false for failure."""

    data: Optional[GetCreateLiveStreamResponseDTO] = None
    r"""Displays the result of the request."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
