"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class MediaIdsRequestTypedDict(TypedDict):
    r"""The list of mediaId(s) you want to perform the operation on."""

    media_ids: List[str]


class MediaIdsRequest(BaseModel):
    r"""The list of mediaId(s) you want to perform the operation on."""

    media_ids: Annotated[List[str], pydantic.Field(alias="mediaIds")]
