"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MetricsOverallmetadataDetailsTypedDict(TypedDict):
    r"""metadata that has to be paased for metric calculations."""

    aggregation: NotRequired[str]
    r"""defines the field or dimension on which the aggregation is to be   applied."""


class MetricsOverallmetadataDetails(BaseModel):
    r"""metadata that has to be paased for metric calculations."""

    aggregation: Optional[str] = None
    r"""defines the field or dimension on which the aggregation is to be   applied."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["aggregation"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
