"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class MetricsOverallDataDetailsTypedDict(TypedDict):
    r"""Retrieves overall values for a specified metric"""

    value: NotRequired[Nullable[float]]
    r"""metric value calculated based on the applied filters."""
    total_watch_time: NotRequired[Nullable[int]]
    r"""Total time watched across all views, represented in milliseconds."""
    unique_views: NotRequired[Nullable[int]]
    r"""The count of unique viewers who interacted with the content."""
    total_views: NotRequired[Nullable[int]]
    r"""The total number of views recorded."""
    total_play_time: NotRequired[Nullable[int]]
    r"""Total time spent playing the video, represented in milliseconds."""
    global_value: NotRequired[Nullable[float]]
    r"""A global metric value that reflects the overall performance of the specified metric across the entire dataset for the given timespan."""


class MetricsOverallDataDetails(BaseModel):
    r"""Retrieves overall values for a specified metric"""

    value: OptionalNullable[float] = UNSET
    r"""metric value calculated based on the applied filters."""

    total_watch_time: Annotated[
        OptionalNullable[int], pydantic.Field(alias="totalWatchTime")
    ] = UNSET
    r"""Total time watched across all views, represented in milliseconds."""

    unique_views: Annotated[
        OptionalNullable[int], pydantic.Field(alias="uniqueViews")
    ] = UNSET
    r"""The count of unique viewers who interacted with the content."""

    total_views: Annotated[
        OptionalNullable[int], pydantic.Field(alias="totalViews")
    ] = UNSET
    r"""The total number of views recorded."""

    total_play_time: Annotated[
        OptionalNullable[int], pydantic.Field(alias="totalPlayTime")
    ] = UNSET
    r"""Total time spent playing the video, represented in milliseconds."""

    global_value: Annotated[
        OptionalNullable[float], pydantic.Field(alias="globalValue")
    ] = UNSET
    r"""A global metric value that reflects the overall performance of the specified metric across the entire dataset for the given timespan."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "value",
                "totalWatchTime",
                "uniqueViews",
                "totalViews",
                "totalPlayTime",
                "globalValue",
            ]
        )
        nullable_fields = set(
            [
                "value",
                "totalWatchTime",
                "uniqueViews",
                "totalViews",
                "totalPlayTime",
                "globalValue",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
