"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class MetricsComparisonDetailsTypedDict(TypedDict):
    r"""Compare multiple metrics across specified dimensions."""

    value: NotRequired[float]
    r"""The specific metric value calculated based on the applied filters."""
    type: NotRequired[str]
    r"""value can be score that ranges from 0 to 100"""
    name: NotRequired[str]
    r"""value can be score that ranges from 0 to 100"""
    metric: NotRequired[str]
    r"""The metric field represents the name of the Key Performance Indicator (KPI) being tracked or analyzed. It identifies a specific measurable aspect of the video playback experience, such as buffering time, video start failure rate, or playback quality.

    """
    measurement: NotRequired[Nullable[str]]
    r"""value can be avg, sum, count or 95th"""
    items: NotRequired[Nullable[List[MetricsComparisonDetailsTypedDict]]]
    r"""Nested comparison items"""


class MetricsComparisonDetails(BaseModel):
    r"""Compare multiple metrics across specified dimensions."""

    value: Optional[float] = None
    r"""The specific metric value calculated based on the applied filters."""

    type: Optional[str] = None
    r"""value can be score that ranges from 0 to 100"""

    name: Optional[str] = None
    r"""value can be score that ranges from 0 to 100"""

    metric: Optional[str] = None
    r"""The metric field represents the name of the Key Performance Indicator (KPI) being tracked or analyzed. It identifies a specific measurable aspect of the video playback experience, such as buffering time, video start failure rate, or playback quality.

    """

    measurement: OptionalNullable[str] = UNSET
    r"""value can be avg, sum, count or 95th"""

    items: OptionalNullable[List[MetricsComparisonDetails]] = UNSET
    r"""Nested comparison items"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["value", "type", "name", "metric", "measurement", "items"]
        )
        nullable_fields = set(["measurement", "items"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
