"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .daterange import DateRange, DateRangeTypedDict
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlaylistByIDResponseMetadataTypedDict(TypedDict):
    r"""Required when the playlist type is `smart`. Media created between `startDate` and `endDate` of `createdDate` is added. Optionally, you can include media based on `updatedDate`."""

    created_date: NotRequired[DateRangeTypedDict]
    r"""Date range with start and end dates."""
    updated_date: NotRequired[DateRangeTypedDict]
    r"""Date range with start and end dates."""


class PlaylistByIDResponseMetadata(BaseModel):
    r"""Required when the playlist type is `smart`. Media created between `startDate` and `endDate` of `createdDate` is added. Optionally, you can include media based on `updatedDate`."""

    created_date: Annotated[
        Optional[DateRange], pydantic.Field(alias="createdDate")
    ] = None
    r"""Date range with start and end dates."""

    updated_date: Annotated[
        Optional[DateRange], pydantic.Field(alias="updatedDate")
    ] = None
    r"""Date range with start and end dates."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdDate", "updatedDate"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
