"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlaybackIDResponseTypedDict(TypedDict):
    r"""A collection of Playback ID objects utilized for crafting HLS playback urls."""

    id: NotRequired[str]
    r"""Unique identifier for the playbackId"""
    access_policy: NotRequired[str]
    r"""Determines if access to the streamed content is kept private or available to all."""


class PlaybackIDResponse(BaseModel):
    r"""A collection of Playback ID objects utilized for crafting HLS playback urls."""

    id: Optional[str] = None
    r"""Unique identifier for the playbackId"""

    access_policy: Annotated[Optional[str], pydantic.Field(alias="accessPolicy")] = None
    r"""Determines if access to the streamed content is kept private or available to all."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "accessPolicy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
