"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from typing import Literal


PlaylistOrder = Literal[
    "createdDate ASC",
    "createdDate DESC",
]
r"""Determines the insertion order of media into playlist."""
