"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SrtPlaybackResponseTypedDict(TypedDict):
    r"""This object contains the livestream playback response details for SRT Protocol"""

    srt_playback_stream_id: NotRequired[str]
    r"""A unique identifier for the SRT playback stream. This ID is used to distinguish between different playback streams"""
    srt_playback_secret: NotRequired[str]
    r"""A playback secret used for securing the SRT playback stream. This ensures that only authorized users can access the playback"""


class SrtPlaybackResponse(BaseModel):
    r"""This object contains the livestream playback response details for SRT Protocol"""

    srt_playback_stream_id: Annotated[
        Optional[str], pydantic.Field(alias="srtPlaybackStreamId")
    ] = None
    r"""A unique identifier for the SRT playback stream. This ID is used to distinguish between different playback streams"""

    srt_playback_secret: Annotated[
        Optional[str], pydantic.Field(alias="srtPlaybackSecret")
    ] = None
    r"""A playback secret used for securing the SRT playback stream. This ensures that only authorized users can access the playback"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["srtPlaybackStreamId", "srtPlaybackSecret"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
