"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


TopErrorDetailsPercentageTypedDict = TypeAliasType(
    "TopErrorDetailsPercentageTypedDict", Union[int, float]
)
r"""views affected by the specific errors."""


TopErrorDetailsPercentage = TypeAliasType(
    "TopErrorDetailsPercentage", Union[int, float]
)
r"""views affected by the specific errors."""


UniqueViewersEffectedPercentageTypedDict = TypeAliasType(
    "UniqueViewersEffectedPercentageTypedDict", Union[int, float]
)
r"""percentage of unique viewers affected by the specific error."""


UniqueViewersEffectedPercentage = TypeAliasType(
    "UniqueViewersEffectedPercentage", Union[int, float]
)
r"""percentage of unique viewers affected by the specific error."""


class TopErrorDetailsTypedDict(TypedDict):
    percentage: NotRequired[Nullable[TopErrorDetailsPercentageTypedDict]]
    r"""views affected by the specific errors."""
    unique_viewers_effected_percentage: NotRequired[
        Nullable[UniqueViewersEffectedPercentageTypedDict]
    ]
    r"""percentage of unique viewers affected by the specific error."""
    notes: NotRequired[Nullable[str]]
    r"""Information about the specific error."""
    message: NotRequired[Nullable[str]]
    r"""error message or description."""
    last_seen: NotRequired[Nullable[str]]
    r"""The timestamp of when the error was last observed."""
    count: NotRequired[Nullable[int]]
    r"""Number of occurrences of the specific error."""
    code: NotRequired[Nullable[str]]
    r"""Error code associated with the specific error."""


class TopErrorDetails(BaseModel):
    percentage: OptionalNullable[TopErrorDetailsPercentage] = UNSET
    r"""views affected by the specific errors."""

    unique_viewers_effected_percentage: Annotated[
        OptionalNullable[UniqueViewersEffectedPercentage],
        pydantic.Field(alias="uniqueViewersEffectedPercentage"),
    ] = UNSET
    r"""percentage of unique viewers affected by the specific error."""

    notes: OptionalNullable[str] = UNSET
    r"""Information about the specific error."""

    message: OptionalNullable[str] = UNSET
    r"""error message or description."""

    last_seen: Annotated[OptionalNullable[str], pydantic.Field(alias="lastSeen")] = (
        UNSET
    )
    r"""The timestamp of when the error was last observed."""

    count: OptionalNullable[int] = UNSET
    r"""Number of occurrences of the specific error."""

    code: OptionalNullable[str] = UNSET
    r"""Error code associated with the specific error."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "percentage",
                "uniqueViewersEffectedPercentage",
                "notes",
                "message",
                "lastSeen",
                "count",
                "code",
            ]
        )
        nullable_fields = set(
            [
                "percentage",
                "uniqueViewersEffectedPercentage",
                "notes",
                "message",
                "lastSeen",
                "count",
                "code",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
