"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from .playlistcreatedresponse import (
    PlaylistCreatedResponse,
    PlaylistCreatedResponseTypedDict,
)
from .updateplaylistrequest import UpdatePlaylistRequest, UpdatePlaylistRequestTypedDict
from fastpix_python.types import BaseModel
from fastpix_python.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class UpdateAPlaylistRequestTypedDict(TypedDict):
    playlist_id: str
    r"""The unique id of the playlist you want to retrieve."""
    body: UpdatePlaylistRequestTypedDict


class UpdateAPlaylistRequest(BaseModel):
    playlist_id: Annotated[
        str,
        pydantic.Field(alias="playlistId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique id of the playlist you want to retrieve."""

    body: Annotated[
        UpdatePlaylistRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


UpdateAPlaylistResponseTypedDict = TypeAliasType(
    "UpdateAPlaylistResponseTypedDict",
    Union[PlaylistCreatedResponseTypedDict, DefaultErrorTypedDict],
)


UpdateAPlaylistResponse = TypeAliasType(
    "UpdateAPlaylistResponse", Union[PlaylistCreatedResponse, DefaultError]
)
