"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .default_error import DefaultError, DefaultErrorTypedDict
from .summaryresponse import SummaryResponse, SummaryResponseTypedDict
from fastpix_python.types import BaseModel, UNSET_SENTINEL
from fastpix_python.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class UpdateMediaSummaryRequestBodyTypedDict(TypedDict):
    generate: bool
    r"""Enable or disable the summary feature for the media. Set to true to enable summary or false to disable.

    """
    summary_length: NotRequired[int]
    r"""Specifies the desired word count for the generated summary.
    - The value must be between **30** and **250** words.

    """


class UpdateMediaSummaryRequestBody(BaseModel):
    generate: bool
    r"""Enable or disable the summary feature for the media. Set to true to enable summary or false to disable.

    """

    summary_length: Annotated[Optional[int], pydantic.Field(alias="summaryLength")] = (
        100
    )
    r"""Specifies the desired word count for the generated summary.
    - The value must be between **30** and **250** words.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["summaryLength"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateMediaSummaryRequestTypedDict(TypedDict):
    media_id: str
    r"""The unique identifier assigned to the media when created. The value must be a valid UUID.

    """
    body: UpdateMediaSummaryRequestBodyTypedDict


class UpdateMediaSummaryRequest(BaseModel):
    media_id: Annotated[
        str,
        pydantic.Field(alias="mediaId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier assigned to the media when created. The value must be a valid UUID.

    """

    body: Annotated[
        UpdateMediaSummaryRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class UpdateMediaSummaryResponseBodyTypedDict(TypedDict):
    r"""Media details updated successfully with the generated summary"""

    success: NotRequired[bool]
    r"""Shows the request status. Returns true for success and false for failure."""
    data: NotRequired[SummaryResponseTypedDict]


class UpdateMediaSummaryResponseBody(BaseModel):
    r"""Media details updated successfully with the generated summary"""

    success: Optional[bool] = None
    r"""Shows the request status. Returns true for success and false for failure."""

    data: Optional[SummaryResponse] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


UpdateMediaSummaryResponseTypedDict = TypeAliasType(
    "UpdateMediaSummaryResponseTypedDict",
    Union[UpdateMediaSummaryResponseBodyTypedDict, DefaultErrorTypedDict],
)


UpdateMediaSummaryResponse = TypeAliasType(
    "UpdateMediaSummaryResponse", Union[UpdateMediaSummaryResponseBody, DefaultError]
)
