"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from .policyaction import PolicyAction
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UserAgentRestrictionsTypedDict(TypedDict):
    r"""Restrictions based on the user agent"""

    default_policy: NotRequired[PolicyAction]
    r"""Policy action type"""
    allow: NotRequired[List[str]]
    r"""A list of user agents that are explicitly allowed access"""
    deny: NotRequired[List[str]]
    r"""A list of user agents that are explicitly denied access"""


class UserAgentRestrictions(BaseModel):
    r"""Restrictions based on the user agent"""

    default_policy: Annotated[
        Optional[PolicyAction], pydantic.Field(alias="defaultPolicy")
    ] = None
    r"""Policy action type"""

    allow: Optional[List[str]] = None
    r"""A list of user agents that are explicitly allowed access"""

    deny: Optional[List[str]] = None
    r"""A list of user agents that are explicitly denied access"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["defaultPolicy", "allow", "deny"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
