"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class VideoTrackForGetAllTypedDict(TypedDict):
    r"""A media consists of different media tracks, like video, audio, and subtitle, all combined."""

    id: NotRequired[str]
    r"""FastPix generates a unique identifier for each track."""
    type: NotRequired[str]
    r"""Defines the type of input. This option is mandatory."""
    width: NotRequired[float]
    r"""Track width denotes the range of widths applicable to a specific track. Currently, this setting can be modified only for video tracks"""
    height: NotRequired[float]
    r"""Track height denotes the range of height applicable to a specific track. Currently, this setting can be modified only for video tracks."""
    frame_rate: NotRequired[str]
    r"""Frame rate quantifies the speed at which frames are displayed per second. It represents the range of frames available for a specific track. The indeterminable frame rate of the input file is indicated by a value of -1."""
    status: NotRequired[str]
    r"""Indicates the current state of the track. 'available' means the track has been processed successfully and is ready to be used or played."""


class VideoTrackForGetAll(BaseModel):
    r"""A media consists of different media tracks, like video, audio, and subtitle, all combined."""

    id: Optional[str] = None
    r"""FastPix generates a unique identifier for each track."""

    type: Optional[str] = None
    r"""Defines the type of input. This option is mandatory."""

    width: Optional[float] = None
    r"""Track width denotes the range of widths applicable to a specific track. Currently, this setting can be modified only for video tracks"""

    height: Optional[float] = None
    r"""Track height denotes the range of height applicable to a specific track. Currently, this setting can be modified only for video tracks."""

    frame_rate: Annotated[Optional[str], pydantic.Field(alias="frameRate")] = None
    r"""Frame rate quantifies the speed at which frames are displayed per second. It represents the range of frames available for a specific track. The indeterminable frame rate of the input file is indicated by a value of -1."""

    status: Optional[str] = None
    r"""Indicates the current state of the track. 'available' means the track has been processed successfully and is ready to be used or played."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "width", "height", "frameRate", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
