"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class VideoInputSegment2TypedDict(TypedDict):
    url: str
    r"""URL of the segment to be added."""
    insert_at_end: bool
    r"""Flag indicating the segment should be inserted at the end."""


class VideoInputSegment2(BaseModel):
    url: str
    r"""URL of the segment to be added."""

    insert_at_end: Annotated[bool, pydantic.Field(alias="insertAtEnd")]
    r"""Flag indicating the segment should be inserted at the end."""


class VideoInputSegment1TypedDict(TypedDict):
    url: str
    r"""URL of the segment to be added."""
    insert_at: int
    r"""The timestamp at which the segment should be inserted."""


class VideoInputSegment1(BaseModel):
    url: str
    r"""URL of the segment to be added."""

    insert_at: Annotated[int, pydantic.Field(alias="insertAt")]
    r"""The timestamp at which the segment should be inserted."""


VideoInputSegmentUnionTypedDict = TypeAliasType(
    "VideoInputSegmentUnionTypedDict",
    Union[VideoInputSegment1TypedDict, VideoInputSegment2TypedDict],
)


VideoInputSegmentUnion = TypeAliasType(
    "VideoInputSegmentUnion", Union[VideoInputSegment1, VideoInputSegment2]
)


class VideoInputTypedDict(TypedDict):
    type: str
    r"""Defines the type of input.

    """
    intro_url: NotRequired[str]
    r"""The url of the intro video which is to be added at the start of the video.

    """
    outro_url: NotRequired[str]
    r"""The url of the outro video which is to be added at the end of the video.

    """
    expunge_segments: NotRequired[List[str]]
    r"""The list of the startTime-endTime of the segments to be removed from the actual video.

    """
    segments: NotRequired[List[VideoInputSegmentUnionTypedDict]]
    r"""A list of media segments to be added or processed. Each segment includes details such as the URL of the media file and instructions on where it should be inserted in the final media composition. A segment can either specify an exact timestamp  (`insertAt`) or indicate that it should be added at the end (`insertAtEnd`)."""


class VideoInput(BaseModel):
    type: str
    r"""Defines the type of input.

    """

    intro_url: Annotated[Optional[str], pydantic.Field(alias="introUrl")] = None
    r"""The url of the intro video which is to be added at the start of the video.

    """

    outro_url: Annotated[Optional[str], pydantic.Field(alias="outroUrl")] = None
    r"""The url of the outro video which is to be added at the end of the video.

    """

    expunge_segments: Annotated[
        Optional[List[str]], pydantic.Field(alias="expungeSegments")
    ] = None
    r"""The list of the startTime-endTime of the segments to be removed from the actual video.

    """

    segments: Optional[List[VideoInputSegmentUnion]] = None
    r"""A list of media segments to be added or processed. Each segment includes details such as the URL of the media file and instructions on where it should be inserted in the final media composition. A segment can either specify an exact timestamp  (`insertAt`) or indicate that it should be added at the end (`insertAtEnd`)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["introUrl", "outroUrl", "expungeSegments", "segments"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
