"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class Custom1TypedDict(TypedDict):
    dimension_name: NotRequired[str]
    r"""Unique identifier for a custom dimension used to categorize or segment analytics data (for example, custom_1).

    """
    display_name: NotRequired[str]
    r"""A user-friendly display label that represents the corresponding custom dimension in analytics dashboards and reports; users can assign a specific name based on their tracking needs.

    """
    value: NotRequired[str]
    r"""Allows assigning user-friendly data values such as email addresses, identifiers, or other meaningful information.

    """


class Custom1(BaseModel):
    dimension_name: Annotated[Optional[str], pydantic.Field(alias="dimensionName")] = (
        None
    )
    r"""Unique identifier for a custom dimension used to categorize or segment analytics data (for example, custom_1).

    """

    display_name: Annotated[Optional[str], pydantic.Field(alias="displayName")] = None
    r"""A user-friendly display label that represents the corresponding custom dimension in analytics dashboards and reports; users can assign a specific name based on their tracking needs.

    """

    value: Optional[str] = None
    r"""Allows assigning user-friendly data values such as email addresses, identifiers, or other meaningful information.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["dimensionName", "displayName", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Custom2TypedDict(TypedDict):
    r"""User defined metadata. Only accessible once it is enabled in the organization settings."""

    custom: NotRequired[Nullable[List[Custom1TypedDict]]]
    r"""A list of custom dimension objects."""


class Custom2(BaseModel):
    r"""User defined metadata. Only accessible once it is enabled in the organization settings."""

    custom: Annotated[
        OptionalNullable[List[Custom1]], pydantic.Field(alias="Custom")
    ] = UNSET
    r"""A list of custom dimension objects."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Custom"])
        nullable_fields = set(["Custom"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


PlayerHeightTypedDict = TypeAliasType("PlayerHeightTypedDict", Union[str, int])
r"""Player Height refers to the vertical dimension, measured in pixels, of the video player as it appears on the webpage.

"""


PlayerHeight = TypeAliasType("PlayerHeight", Union[str, int])
r"""Player Height refers to the vertical dimension, measured in pixels, of the video player as it appears on the webpage.

"""


PlayerViewCountTypedDict = TypeAliasType("PlayerViewCountTypedDict", Union[str, int])
r"""Represents the total number of times the video player has been initialized or viewed for a specific session or video. This metric helps track playback engagement and identify view patterns across different players or sessions.

"""


PlayerViewCount = TypeAliasType("PlayerViewCount", Union[str, int])
r"""Represents the total number of times the video player has been initialized or viewed for a specific session or video. This metric helps track playback engagement and identify view patterns across different players or sessions.

"""


PropertyIDTypedDict = TypeAliasType("PropertyIDTypedDict", Union[str, int])
r"""Represents the unique identifier assigned to a FastPix property, which is associated with a specific workspace or project. It helps link playback and analytics data to the correct property configuration.

"""


PropertyID = TypeAliasType("PropertyID", Union[str, int])
r"""Represents the unique identifier assigned to a FastPix property, which is associated with a specific workspace or project. It helps link playback and analytics data to the correct property configuration.

"""


ViewerTimeTypedDict = TypeAliasType("ViewerTimeTypedDict", Union[str, int])
r"""The unix epoch timestamp which represents the actual time the event has occurred.

"""


ViewerTime = TypeAliasType("ViewerTime", Union[str, int])
r"""The unix epoch timestamp which represents the actual time the event has occurred.

"""


EventTimeTypedDict = TypeAliasType("EventTimeTypedDict", Union[str, int])
r"""The unix epoch timestamp when the event was captured.

"""


EventTime = TypeAliasType("EventTime", Union[str, int])
r"""The unix epoch timestamp when the event was captured.

"""


class EventTypedDict(TypedDict):
    player_playhead_time: NotRequired[Nullable[int]]
    r"""The player_playhead_time represents the current position of the playhead (the point in the video that is being watched) on the video seekbar, measured in milliseconds. This value indicates how far into the video playback has progressed at any given moment.

    """
    event_name: NotRequired[Nullable[str]]
    r"""Name of the event.

    """
    event_details: NotRequired[Dict[str, Any]]
    viewer_time: NotRequired[Nullable[ViewerTimeTypedDict]]
    r"""The unix epoch timestamp which represents the actual time the event has occurred.

    """
    event_time: NotRequired[Nullable[EventTimeTypedDict]]
    r"""The unix epoch timestamp when the event was captured.

    """


class Event(BaseModel):
    player_playhead_time: OptionalNullable[int] = UNSET
    r"""The player_playhead_time represents the current position of the playhead (the point in the video that is being watched) on the video seekbar, measured in milliseconds. This value indicates how far into the video playback has progressed at any given moment.

    """

    event_name: OptionalNullable[str] = UNSET
    r"""Name of the event.

    """

    event_details: Optional[Dict[str, Any]] = None

    viewer_time: OptionalNullable[ViewerTime] = UNSET
    r"""The unix epoch timestamp which represents the actual time the event has occurred.

    """

    event_time: OptionalNullable[EventTime] = UNSET
    r"""The unix epoch timestamp when the event was captured.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "player_playhead_time",
                "event_name",
                "event_details",
                "viewer_time",
                "event_time",
            ]
        )
        nullable_fields = set(
            ["player_playhead_time", "event_name", "viewer_time", "event_time"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ViewsTypedDict(TypedDict):
    r"""Displays the result of the request."""

    asn_id: NotRequired[Nullable[int]]
    r"""The unique identifier assigned to an Autonomous System (AS) on the Internet. The ASN is used to identify and exchange routing information between different networks.

    """
    asn_name: NotRequired[Nullable[str]]
    r"""The Name associated with the asnId.

    """
    average_bitrate: NotRequired[Nullable[float]]
    r"""Average Bitrate represents the average bitrate of the video content watched by the viewer, expressed in bits per second (bps). This metric provides insight into the quality of the video stream.

    """
    avg_downscaling: NotRequired[Nullable[float]]
    r"""Average Downscaling refers to the average reduction in video resolution or quality during the playback of video content.

    """
    avg_request_latency: NotRequired[Nullable[float]]
    r"""Average Request Latency average time it takes for a request to be made and processed during video playback

    """
    avg_request_throughput: NotRequired[Nullable[float]]
    r"""Average Request Throughput refers to the average throughput or data transfer rate of HTTP requests made during video playback

    """
    avg_upscaling: NotRequired[Nullable[float]]
    r"""Average Upscaling refers to the average resolution of the video source is lower than the resolution of the playback device or screen.

    """
    beacon_domain: NotRequired[str]
    r"""Beacon Domain specifies the domain endpoint used by the player or SDK to send analytics or tracking beacons for playback events.

    """
    browser_engine: NotRequired[Nullable[str]]
    r"""Browser Engine denotes the rendering engine used by the browser (e.g., Blink, Gecko, WebKit).

    """
    browser_name: NotRequired[Nullable[str]]
    r"""Browser Name denotes the software application utilized by the viewer to access and watch the video content

    """
    browser_version: NotRequired[Nullable[str]]
    r"""Browser Version signifies the specific version of the browser software employed by the viewer

    """
    buffer_count: NotRequired[Nullable[int]]
    r"""Buffer Count represents the number of rebuffering events occurring during the video view.

    """
    buffer_fill: NotRequired[Nullable[int]]
    r"""Buffer Fill indicates the total time, in milliseconds, that viewers wait for rebuffering per video view.

    """
    buffer_frequency: NotRequired[Nullable[float]]
    r"""Buffer Frequency measures the rate at which rebuffering events occur, expressed as events per millisecond.

    """
    buffer_ratio: NotRequired[Nullable[float]]
    r"""Buffer Ratio refers to the percentage of time during video playback where the viewer experiences buffering or rebuffering events.

    """
    cdn: NotRequired[Nullable[str]]
    r"""Content Delivery Network (CDN) refers to the network infrastructure responsible for delivering the video content to the viewer.

    """
    city: NotRequired[Nullable[str]]
    r"""City indicates the geographical location of the viewer accessing the video content.

    """
    connection_type: NotRequired[Nullable[str]]
    r"""Connection Type signifies the type of network connection utilized by the viewers device

    """
    continent: NotRequired[Nullable[str]]
    r"""Continent represents the continent name of the viewer accessing the video content.

    """
    country: NotRequired[Nullable[str]]
    r"""Country represents the coded text that represents the country name of viewer accessing the video content.

    """
    country_code: NotRequired[Nullable[str]]
    r"""Country Code denotes the two-letter ISO code representing the country of origin for the viewer accessing the video content.

    """
    custom: NotRequired[Custom2TypedDict]
    r"""User defined metadata. Only accessible once it is enabled in the organization settings.

    """
    device_manufacturer: NotRequired[Nullable[str]]
    r"""Device Manufacturer indicates the brand or manufacturer of the device used by the viewer.

    """
    device_model: NotRequired[Nullable[str]]
    r"""Device Model represents the specific model of the device used by the viewer.

    """
    device_name: NotRequired[Nullable[str]]
    r"""Device Name refers to the name or label assigned to the device used by the viewer.

    """
    device_type: NotRequired[Nullable[str]]
    r"""Device Type denotes the classification of the device used by the viewer

    """
    drm_type: NotRequired[Nullable[str]]
    r"""DRM Type indicates the type of Digital Rights Management (DRM) utilized during video playback

    """
    dropped_frame_count: NotRequired[Nullable[int]]
    r"""Dropped Frame Count represents the number of frames dropped by the video player during playback.

    """
    error_code: NotRequired[Nullable[str]]
    r"""Error Code is an identifier representing a specific type of error that occurred during video playback, potentially leading to playback failure.

    """
    error_context: NotRequired[Nullable[str]]
    r"""Specifies the component or stage where the playback error originated, such as streaming, cdn, decoder, or player. This context helps diagnose whether the failure was caused by delivery issues, playback logic, or media decoding problems within the FastPix streaming pipeline.

    """
    error_id: NotRequired[Nullable[int]]
    r"""The unique identifier which identifies each type of error that occurs.

    """
    error_message: NotRequired[Nullable[str]]
    r"""Error Message is a descriptive message generated by the video player when an error occurs during playback, associated with an error code.

    """
    exit_before_video_start: NotRequired[bool]
    r"""Exit Before Video Start indicates whether a viewer abandoned the video before it started playing, typically due to long loading times.

    """
    experiment_name: NotRequired[Nullable[str]]
    r"""Experiment Name is used in A/B testing scenarios to categorize video views into different experiments.

    """
    fp_api_version: NotRequired[Nullable[str]]
    r"""Specifies the version of the FastPix API used during data collection or playback reporting. This helps ensure compatibility and traceability between client SDK versions and backend processing.

    """
    fp_embed: NotRequired[Nullable[bool]]
    r"""Identifies the type or source of the FastPix player embed used for playback — for example, whether the video was played through a direct player integration, an iframe, or a third-party embedded context. This helps differentiate playback environments and measure performance across embed types.

    """
    fp_embed_version: NotRequired[Nullable[str]]
    r"""Specifies the version of the FastPix embed script or SDK used to initialize the player. This helps track playback behavior and debug issues across different embed versions or deployment environments.

    """
    fp_live_stream_id: NotRequired[Nullable[str]]
    r"""FastPix Live Stream ID is the unique identifier associated with a live stream video media within the FastPix Video Platform.

    """
    fp_playback_id: NotRequired[Nullable[str]]
    r"""FastPix Playback ID refers to the unique identifier associated with the playback instance of a video, particularly used in FastPix Video Platform.

    """
    fp_sdk: NotRequired[Nullable[str]]
    r"""FastPix SDK Name identifies the name of the FastPix Player SDK utilized within the player workspace.

    """
    fp_sdk_version: NotRequired[Nullable[str]]
    r"""FastPix SDK Version specifies the version of the FastPix Player SDK integrated into the player.

    """
    fp_viewer_id: NotRequired[Nullable[str]]
    r"""Represents a unique, anonymized identifier assigned to each viewer by the FastPix SDK. This ID helps correlate multiple playback sessions or events to the same viewer across sessions or devices without exposing any personal information.

    """
    insert_timestamp: NotRequired[str]
    r"""Insert Timestamp refers to the time instance when the view is started.

    """
    ip_address: NotRequired[str]
    r"""Represents the IP address of the user or device that initiated the playback session.

    """
    jump_latency: NotRequired[Nullable[float]]
    r"""Jump Latency refers to the delay or latency experienced when there is a jump or seek action performed by the viewer while watching a video.

    """
    latitude: NotRequired[Nullable[str]]
    r"""Latitude refers to the geographical coordinate representing the north-south position of the viewers location, truncated to one decimal place.

    """
    live_stream_latency: NotRequired[Nullable[int]]
    r"""Live Stream Latency measures the average time taken from the point of ingest to the point of display for live stream video views.

    """
    longitude: NotRequired[Nullable[str]]
    r"""Longitude denotes the geographical coordinate representing the east-west position of the viewers location, truncated to one decimal place.

    """
    max_downscaling: NotRequired[Nullable[float]]
    r"""Maximum Downscale Percentage represents the highest percentage of downscaling applied to the video during the view.

    """
    max_request_latency: NotRequired[Nullable[float]]
    r"""Max Request Latency refers to the maximum rate of data transfer (throughput) during requests made by the playback.

    """
    max_upscaling: NotRequired[Nullable[float]]
    r"""Maximum Upscale Percentage represents the highest percentage of upscaling applied to the video during the view.

    """
    media_id: NotRequired[Nullable[str]]
    r"""The media Id value if the video asset is internal to FastPix.

    """
    os_name: NotRequired[Nullable[str]]
    r"""Operating System signifies the name of software platform utilized by the viewer.

    """
    os_version: NotRequired[str]
    r"""Operating System Version specifies the specific version of the operating system being used by the viewer

    """
    page_context: NotRequired[Nullable[str]]
    r"""Page Context provides contextual information about the type of page being accessed.

    """
    page_load_time: NotRequired[Nullable[int]]
    r"""Page Load Time measures the time from when the user initiates loading the page to when all resources are loaded on the page.

    """
    playback_score: NotRequired[Nullable[float]]
    r"""Playback Success Score represents a numerical value indicating the success or quality of the video playback experience.

    """
    player_autoplay_on: NotRequired[bool]
    r"""Player Autoplay On indicates whether the video player automatically initiated playback of the video content.

    """
    player_height: NotRequired[Nullable[PlayerHeightTypedDict]]
    r"""Player Height refers to the vertical dimension, measured in pixels, of the video player as it appears on the webpage.

    """
    player_initialization_time: NotRequired[Nullable[int]]
    r"""Player Initialization Time measures the duration, in milliseconds, from the initialization of the player within the webpage to its readiness to receive further instructions.

    """
    player_instance_id: NotRequired[Nullable[str]]
    r"""Player Instance ID is a unique identifier that distinguishes each instance of the Player class created when initializing a video.

    """
    player_language: NotRequired[Nullable[str]]
    r"""Player Language indicates the language used for text elements within the video player interface.

    """
    player_name: NotRequired[Nullable[str]]
    r"""Player Name serves to differentiate various configurations or types of players used across the website or application.

    """
    player_poster: NotRequired[Nullable[str]]
    r"""Player Poster refers to the image displayed as a preview before the video playback begins.

    """
    player_preload_on: NotRequired[bool]
    r"""Player Preload On indicates whether the player is configured to preload the video content upon page load.

    """
    player_remote_played: NotRequired[bool]
    r"""Player Remote Played specifies if the video is being remotely played to devices such as AirPlay or Chromecast, obtained from the SDK.

    """
    player_resolution: NotRequired[Nullable[str]]
    r"""Player Resolution refers to the resolution of the video player window or viewport where the video content is being displayed.

    """
    player_software_name: NotRequired[Nullable[str]]
    r"""Represents the name of the video player software or framework used for playback (for example, HTML5, HLS.js, Shaka Player).

    """
    player_software_version: NotRequired[Nullable[str]]
    r"""Player Software Version indicates the version number of the player software installed.

    """
    player_source_domain: NotRequired[Nullable[str]]
    r"""Specifies the domain or source from which the player was loaded or embedded (for example, stream.fastpix.io or a customer’s custom domain). This helps identify the playback origin and differentiate between various deployment environments.

    """
    player_source_height: NotRequired[Nullable[int]]
    r"""Player Source Height denotes the vertical dimension, measured in pixels, of the source video content being transmitted to the player.

    """
    player_source_width: NotRequired[Nullable[int]]
    r"""Player Source Width represents the width of the source video as perceived by the player, typically measured in pixels.

    """
    player_version: NotRequired[Nullable[str]]
    r"""Player Version indicates the version of the player used to render the video content. It is often utilized for performance comparison between different player versions.

    """
    player_view_count: NotRequired[Nullable[PlayerViewCountTypedDict]]
    r"""Represents the total number of times the video player has been initialized or viewed for a specific session or video. This metric helps track playback engagement and identify view patterns across different players or sessions.

    """
    player_width: NotRequired[Nullable[int]]
    r"""Player Width refers to the width of the player displayed within the webpage, measured in pixels.

    """
    property_id: NotRequired[Nullable[PropertyIDTypedDict]]
    r"""Represents the unique identifier assigned to a FastPix property, which is associated with a specific workspace or project. It helps link playback and analytics data to the correct property configuration.

    """
    quality_of_experience_score: NotRequired[Nullable[float]]
    r"""Quality Of Experience Score quantifies the overall viewer experience based on various metrics, providing a decimal score to assess the quality of the viewing experience.

    """
    region: NotRequired[Nullable[str]]
    r"""Region denotes the geographical region of the viewer accessing the video content.

    """
    render_quality_score: NotRequired[Nullable[float]]
    r"""Render Quality Score is a decimal value representing the score indicating the perceived quality of the video.

    """
    session_id: NotRequired[Nullable[str]]
    r"""Session ID refers to the unique identifier tracking a viewers session within the FastPix platform.

    """
    sign: NotRequired[Nullable[str]]
    r"""Represents a cryptographic signature used to verify the authenticity and integrity of the playback or API request within the FastPix platform. It ensures that the data has not been tampered with and originates from a trusted source.

    """
    stability_score: NotRequired[Nullable[float]]
    r"""Stability Score quantifies the smoothness of video playback, typically represented as a decimal value.

    """
    startup_score: NotRequired[Nullable[float]]
    r"""Startup Score evaluates the startup performance of the player, usually represented as a decimal value

    """
    sub_property_id: NotRequired[Nullable[str]]
    r"""Sub Property ID denotes the unique identifier assigned to FastPix properties, previously linked with a specific workspace.

    """
    total_startup_time: NotRequired[Nullable[int]]
    r"""Represents the total time (in milliseconds) taken for the video player to start playback from the moment the user initiates the session. This includes loading, buffering, and initialization delays before the first frame is rendered.

    """
    updated_timestamp: NotRequired[Nullable[str]]
    r"""Updated Timestamp refers to when the record is updated to a particular Video.

    """
    used_full_screen: NotRequired[bool]
    r"""Used Fullscreen denotes whether the viewer utilized the full-screen mode while watching the video.

    """
    user_agent: NotRequired[Nullable[str]]
    r"""User Agent represents the user agent string transmitted by the viewers device to identify itself to the server, typically including information about the device and browser.

    """
    video_content_type: NotRequired[Nullable[str]]
    r"""Video Content Type specifies the classification of the video content.

    """
    video_duration: NotRequired[Nullable[int]]
    r"""Video Duration represents the length of the video, provided in milliseconds, typically supplied to FastPix through custom metadata.

    """
    video_encoding_variant: NotRequired[Nullable[str]]
    r"""Indicates the specific encoding variant or rendition of the video being played, such as resolution, bitrate, or codec type. This helps identify which encoded version of the video was selected for playback.

    """
    video_id: NotRequired[Nullable[str]]
    r"""Video ID refers to an internal identifier assigned by the user or system to uniquely identify a particular video.

    """
    video_language: NotRequired[Nullable[str]]
    r"""Video Language denotes the primary audio language of the video content, assuming it remains unchanged after playback initiation.

    """
    video_producer: NotRequired[Nullable[str]]
    r"""Specifies the creator or source responsible for producing the video content.

    """
    video_resolution: NotRequired[Nullable[str]]
    r"""Video Resolution refers to the resolution of the video being played.

    """
    video_series: NotRequired[Nullable[str]]
    r"""Video Series denotes the name of a series to which the video content belongs.

    """
    video_source_domain: NotRequired[Nullable[str]]
    r"""Video Source Domain identifies the domain from which the video source originates.

    """
    video_source_duration: NotRequired[Nullable[int]]
    r"""Video Source Duration represents the duration of the video source content, measured in milliseconds.

    """
    video_source_hostname: NotRequired[Nullable[str]]
    r"""Video Source Hostname represents the hostname of the video.

    """
    video_source_stream_type: NotRequired[Nullable[str]]
    r"""Video Source Stream Type denotes the type of stream used by the player, although it is currently unused.

    """
    video_source_type: NotRequired[Nullable[str]]
    r"""Video Source Type denotes the format of the video source as determined by the player.

    """
    video_source_url: NotRequired[Nullable[str]]
    r"""Video Source URL refers to the URL of the video source accessed by the player.

    """
    video_startup_failed: NotRequired[bool]
    r"""Video Startup Failure is a boolean metric indicating whether a viewer encountered an error before the first frame of the video commenced playback.

    """
    video_startup_time: NotRequired[Nullable[int]]
    r"""Video Startup Time measures the duration, in milliseconds, from the initialization of the player within the webpage to its readiness to receive further instructions.

    """
    video_title: NotRequired[Nullable[str]]
    r"""Video Title refers to the title of the video content being viewed.

    """
    video_variant_id: NotRequired[Nullable[str]]
    r"""Represents the unique identifier for the specific video variant or rendition being played. Each variant corresponds to a particular encoding configuration, such as resolution or bitrate, used for adaptive streaming and performance tracking.

    """
    video_variant_name: NotRequired[Nullable[str]]
    r"""Specifies the human-readable name of the video variant or rendition being played (for example, “1080p H.264” or “720p AV1”). This helps identify the playback quality or encoding configuration selected during streaming.

    """
    view_end: NotRequired[Nullable[str]]
    r"""View End refers to the date and time, in Coordinated Universal Time (UTC), when the video viewing session concluded.

    """
    view_has_ad: NotRequired[bool]
    r"""View Has Ad is a boolean metric indicating whether an advertisement played or attempted to play during the video view.

    """
    view_has_error: NotRequired[bool]
    r"""Indicates whether any playback error occurred during the video view. This boolean flag helps identify failed or interrupted playback sessions caused by player, network, or media-related issues.

    """
    view_id: NotRequired[str]
    r"""View ID is a unique identifier assigned to each individual video viewing session.

    """
    view_max_playhead_position: NotRequired[Nullable[int]]
    r"""View Max Playhead Position represents the furthest point reached by the playhead during the video view, measured in milliseconds.

    """
    view_page_url: NotRequired[Nullable[str]]
    r"""View Page URL denotes the URL address of the web page where the video content is being accessed.

    """
    view_playing_time: NotRequired[Nullable[int]]
    r"""Playing Time denotes the total duration of time the video content was actively playing during the view, excluding time spent buffering, seeking, or joining.

    """
    view_seeked_count: NotRequired[Nullable[int]]
    r"""View Seeked Count signifies the number of times the viewer attempted to seek to a new location within the video.

    """
    view_seeked_duration: NotRequired[Nullable[int]]
    r"""View Seeked Duration indicates the total duration of time spent waiting for playback to resume after the viewer seeks to a new location. Seek Latency metric in the Dashboard is derived by dividing this value by the view_seek_count.

    """
    view_session_id: NotRequired[Nullable[str]]
    r"""Represents the unique identifier assigned to a single playback session within FastPix. This ID is used to correlate all playback events, errors, and metrics that occur during the same viewing session.

    """
    view_start: NotRequired[Nullable[str]]
    r"""View Start refers to the date and time, in Coordinated Universal Time (UTC), when the video viewing session commenced.

    """
    view_total_content_playback_time: NotRequired[Nullable[int]]
    r"""View Total Content Playback Time represents the cumulative duration of video content watched by the viewer, measured in milliseconds. This metric is internally utilized to calculate upscale and downscale percentages.

    """
    viewer_id: NotRequired[Nullable[str]]
    r"""Viewer ID refers to a customer-defined identifier representing the viewer who is watching the video stream. It must be anonymized and not contain any personally identifiable information.

    """
    watch_time: NotRequired[Nullable[int]]
    r"""Total Watch Time denotes the total duration of video content watched by the viewer, encompassing startup time, playing time, and potential rebuffering time, measured in milliseconds.

    """
    workspace_id: NotRequired[str]
    r"""It is a unique identifier associated with a specific workspace within the FastPix platform.

    """
    events: NotRequired[List[EventTypedDict]]
    r"""Events specifies the order of events journey of the video playback

    """


class Views(BaseModel):
    r"""Displays the result of the request."""

    asn_id: Annotated[OptionalNullable[int], pydantic.Field(alias="asnId")] = UNSET
    r"""The unique identifier assigned to an Autonomous System (AS) on the Internet. The ASN is used to identify and exchange routing information between different networks.

    """

    asn_name: Annotated[OptionalNullable[str], pydantic.Field(alias="asnName")] = UNSET
    r"""The Name associated with the asnId.

    """

    average_bitrate: Annotated[
        OptionalNullable[float], pydantic.Field(alias="averageBitrate")
    ] = UNSET
    r"""Average Bitrate represents the average bitrate of the video content watched by the viewer, expressed in bits per second (bps). This metric provides insight into the quality of the video stream.

    """

    avg_downscaling: Annotated[
        OptionalNullable[float], pydantic.Field(alias="avgDownscaling")
    ] = UNSET
    r"""Average Downscaling refers to the average reduction in video resolution or quality during the playback of video content.

    """

    avg_request_latency: Annotated[
        OptionalNullable[float], pydantic.Field(alias="avgRequestLatency")
    ] = UNSET
    r"""Average Request Latency average time it takes for a request to be made and processed during video playback

    """

    avg_request_throughput: Annotated[
        OptionalNullable[float], pydantic.Field(alias="avgRequestThroughput")
    ] = UNSET
    r"""Average Request Throughput refers to the average throughput or data transfer rate of HTTP requests made during video playback

    """

    avg_upscaling: Annotated[
        OptionalNullable[float], pydantic.Field(alias="avgUpscaling")
    ] = UNSET
    r"""Average Upscaling refers to the average resolution of the video source is lower than the resolution of the playback device or screen.

    """

    beacon_domain: Annotated[Optional[str], pydantic.Field(alias="beaconDomain")] = None
    r"""Beacon Domain specifies the domain endpoint used by the player or SDK to send analytics or tracking beacons for playback events.

    """

    browser_engine: Annotated[
        OptionalNullable[str], pydantic.Field(alias="browserEngine")
    ] = UNSET
    r"""Browser Engine denotes the rendering engine used by the browser (e.g., Blink, Gecko, WebKit).

    """

    browser_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="browserName")
    ] = UNSET
    r"""Browser Name denotes the software application utilized by the viewer to access and watch the video content

    """

    browser_version: Annotated[
        OptionalNullable[str], pydantic.Field(alias="browserVersion")
    ] = UNSET
    r"""Browser Version signifies the specific version of the browser software employed by the viewer

    """

    buffer_count: Annotated[
        OptionalNullable[int], pydantic.Field(alias="bufferCount")
    ] = UNSET
    r"""Buffer Count represents the number of rebuffering events occurring during the video view.

    """

    buffer_fill: Annotated[
        OptionalNullable[int], pydantic.Field(alias="bufferFill")
    ] = UNSET
    r"""Buffer Fill indicates the total time, in milliseconds, that viewers wait for rebuffering per video view.

    """

    buffer_frequency: Annotated[
        OptionalNullable[float], pydantic.Field(alias="bufferFrequency")
    ] = UNSET
    r"""Buffer Frequency measures the rate at which rebuffering events occur, expressed as events per millisecond.

    """

    buffer_ratio: Annotated[
        OptionalNullable[float], pydantic.Field(alias="bufferRatio")
    ] = UNSET
    r"""Buffer Ratio refers to the percentage of time during video playback where the viewer experiences buffering or rebuffering events.

    """

    cdn: OptionalNullable[str] = UNSET
    r"""Content Delivery Network (CDN) refers to the network infrastructure responsible for delivering the video content to the viewer.

    """

    city: OptionalNullable[str] = UNSET
    r"""City indicates the geographical location of the viewer accessing the video content.

    """

    connection_type: Annotated[
        OptionalNullable[str], pydantic.Field(alias="connectionType")
    ] = UNSET
    r"""Connection Type signifies the type of network connection utilized by the viewers device

    """

    continent: OptionalNullable[str] = UNSET
    r"""Continent represents the continent name of the viewer accessing the video content.

    """

    country: OptionalNullable[str] = UNSET
    r"""Country represents the coded text that represents the country name of viewer accessing the video content.

    """

    country_code: Annotated[
        OptionalNullable[str], pydantic.Field(alias="countryCode")
    ] = UNSET
    r"""Country Code denotes the two-letter ISO code representing the country of origin for the viewer accessing the video content.

    """

    custom: Optional[Custom2] = None
    r"""User defined metadata. Only accessible once it is enabled in the organization settings.

    """

    device_manufacturer: Annotated[
        OptionalNullable[str], pydantic.Field(alias="deviceManufacturer")
    ] = UNSET
    r"""Device Manufacturer indicates the brand or manufacturer of the device used by the viewer.

    """

    device_model: Annotated[
        OptionalNullable[str], pydantic.Field(alias="deviceModel")
    ] = UNSET
    r"""Device Model represents the specific model of the device used by the viewer.

    """

    device_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="deviceName")
    ] = UNSET
    r"""Device Name refers to the name or label assigned to the device used by the viewer.

    """

    device_type: Annotated[
        OptionalNullable[str], pydantic.Field(alias="deviceType")
    ] = UNSET
    r"""Device Type denotes the classification of the device used by the viewer

    """

    drm_type: Annotated[OptionalNullable[str], pydantic.Field(alias="drmType")] = UNSET
    r"""DRM Type indicates the type of Digital Rights Management (DRM) utilized during video playback

    """

    dropped_frame_count: Annotated[
        OptionalNullable[int], pydantic.Field(alias="droppedFrameCount")
    ] = UNSET
    r"""Dropped Frame Count represents the number of frames dropped by the video player during playback.

    """

    error_code: Annotated[OptionalNullable[str], pydantic.Field(alias="errorCode")] = (
        UNSET
    )
    r"""Error Code is an identifier representing a specific type of error that occurred during video playback, potentially leading to playback failure.

    """

    error_context: Annotated[
        OptionalNullable[str], pydantic.Field(alias="errorContext")
    ] = UNSET
    r"""Specifies the component or stage where the playback error originated, such as streaming, cdn, decoder, or player. This context helps diagnose whether the failure was caused by delivery issues, playback logic, or media decoding problems within the FastPix streaming pipeline.

    """

    error_id: Annotated[OptionalNullable[int], pydantic.Field(alias="errorId")] = UNSET
    r"""The unique identifier which identifies each type of error that occurs.

    """

    error_message: Annotated[
        OptionalNullable[str], pydantic.Field(alias="errorMessage")
    ] = UNSET
    r"""Error Message is a descriptive message generated by the video player when an error occurs during playback, associated with an error code.

    """

    exit_before_video_start: Annotated[
        Optional[bool], pydantic.Field(alias="exitBeforeVideoStart")
    ] = None
    r"""Exit Before Video Start indicates whether a viewer abandoned the video before it started playing, typically due to long loading times.

    """

    experiment_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="experimentName")
    ] = UNSET
    r"""Experiment Name is used in A/B testing scenarios to categorize video views into different experiments.

    """

    fp_api_version: Annotated[
        OptionalNullable[str], pydantic.Field(alias="fpApiVersion")
    ] = UNSET
    r"""Specifies the version of the FastPix API used during data collection or playback reporting. This helps ensure compatibility and traceability between client SDK versions and backend processing.

    """

    fp_embed: Annotated[OptionalNullable[bool], pydantic.Field(alias="fpEmbed")] = UNSET
    r"""Identifies the type or source of the FastPix player embed used for playback — for example, whether the video was played through a direct player integration, an iframe, or a third-party embedded context. This helps differentiate playback environments and measure performance across embed types.

    """

    fp_embed_version: Annotated[
        OptionalNullable[str], pydantic.Field(alias="fpEmbedVersion")
    ] = UNSET
    r"""Specifies the version of the FastPix embed script or SDK used to initialize the player. This helps track playback behavior and debug issues across different embed versions or deployment environments.

    """

    fp_live_stream_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="fpLiveStreamId")
    ] = UNSET
    r"""FastPix Live Stream ID is the unique identifier associated with a live stream video media within the FastPix Video Platform.

    """

    fp_playback_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="fpPlaybackId")
    ] = UNSET
    r"""FastPix Playback ID refers to the unique identifier associated with the playback instance of a video, particularly used in FastPix Video Platform.

    """

    fp_sdk: Annotated[OptionalNullable[str], pydantic.Field(alias="fpSdk")] = UNSET
    r"""FastPix SDK Name identifies the name of the FastPix Player SDK utilized within the player workspace.

    """

    fp_sdk_version: Annotated[
        OptionalNullable[str], pydantic.Field(alias="fpSdkVersion")
    ] = UNSET
    r"""FastPix SDK Version specifies the version of the FastPix Player SDK integrated into the player.

    """

    fp_viewer_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="fpViewerId")
    ] = UNSET
    r"""Represents a unique, anonymized identifier assigned to each viewer by the FastPix SDK. This ID helps correlate multiple playback sessions or events to the same viewer across sessions or devices without exposing any personal information.

    """

    insert_timestamp: Annotated[
        Optional[str], pydantic.Field(alias="insertTimestamp")
    ] = None
    r"""Insert Timestamp refers to the time instance when the view is started.

    """

    ip_address: Annotated[Optional[str], pydantic.Field(alias="ipAddress")] = None
    r"""Represents the IP address of the user or device that initiated the playback session.

    """

    jump_latency: Annotated[
        OptionalNullable[float], pydantic.Field(alias="jumpLatency")
    ] = UNSET
    r"""Jump Latency refers to the delay or latency experienced when there is a jump or seek action performed by the viewer while watching a video.

    """

    latitude: OptionalNullable[str] = UNSET
    r"""Latitude refers to the geographical coordinate representing the north-south position of the viewers location, truncated to one decimal place.

    """

    live_stream_latency: Annotated[
        OptionalNullable[int], pydantic.Field(alias="liveStreamLatency")
    ] = UNSET
    r"""Live Stream Latency measures the average time taken from the point of ingest to the point of display for live stream video views.

    """

    longitude: OptionalNullable[str] = UNSET
    r"""Longitude denotes the geographical coordinate representing the east-west position of the viewers location, truncated to one decimal place.

    """

    max_downscaling: Annotated[
        OptionalNullable[float], pydantic.Field(alias="maxDownscaling")
    ] = UNSET
    r"""Maximum Downscale Percentage represents the highest percentage of downscaling applied to the video during the view.

    """

    max_request_latency: Annotated[
        OptionalNullable[float], pydantic.Field(alias="maxRequestLatency")
    ] = UNSET
    r"""Max Request Latency refers to the maximum rate of data transfer (throughput) during requests made by the playback.

    """

    max_upscaling: Annotated[
        OptionalNullable[float], pydantic.Field(alias="maxUpscaling")
    ] = UNSET
    r"""Maximum Upscale Percentage represents the highest percentage of upscaling applied to the video during the view.

    """

    media_id: Annotated[OptionalNullable[str], pydantic.Field(alias="mediaId")] = UNSET
    r"""The media Id value if the video asset is internal to FastPix.

    """

    os_name: Annotated[OptionalNullable[str], pydantic.Field(alias="osName")] = UNSET
    r"""Operating System signifies the name of software platform utilized by the viewer.

    """

    os_version: Annotated[Optional[str], pydantic.Field(alias="osVersion")] = None
    r"""Operating System Version specifies the specific version of the operating system being used by the viewer

    """

    page_context: Annotated[
        OptionalNullable[str], pydantic.Field(alias="pageContext")
    ] = UNSET
    r"""Page Context provides contextual information about the type of page being accessed.

    """

    page_load_time: Annotated[
        OptionalNullable[int], pydantic.Field(alias="pageLoadTime")
    ] = UNSET
    r"""Page Load Time measures the time from when the user initiates loading the page to when all resources are loaded on the page.

    """

    playback_score: Annotated[
        OptionalNullable[float], pydantic.Field(alias="playbackScore")
    ] = UNSET
    r"""Playback Success Score represents a numerical value indicating the success or quality of the video playback experience.

    """

    player_autoplay_on: Annotated[
        Optional[bool], pydantic.Field(alias="playerAutoplayOn")
    ] = None
    r"""Player Autoplay On indicates whether the video player automatically initiated playback of the video content.

    """

    player_height: Annotated[
        OptionalNullable[PlayerHeight], pydantic.Field(alias="playerHeight")
    ] = UNSET
    r"""Player Height refers to the vertical dimension, measured in pixels, of the video player as it appears on the webpage.

    """

    player_initialization_time: Annotated[
        OptionalNullable[int], pydantic.Field(alias="playerInitializationTime")
    ] = UNSET
    r"""Player Initialization Time measures the duration, in milliseconds, from the initialization of the player within the webpage to its readiness to receive further instructions.

    """

    player_instance_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="playerInstanceId")
    ] = UNSET
    r"""Player Instance ID is a unique identifier that distinguishes each instance of the Player class created when initializing a video.

    """

    player_language: Annotated[
        OptionalNullable[str], pydantic.Field(alias="playerLanguage")
    ] = UNSET
    r"""Player Language indicates the language used for text elements within the video player interface.

    """

    player_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="playerName")
    ] = UNSET
    r"""Player Name serves to differentiate various configurations or types of players used across the website or application.

    """

    player_poster: Annotated[
        OptionalNullable[str], pydantic.Field(alias="playerPoster")
    ] = UNSET
    r"""Player Poster refers to the image displayed as a preview before the video playback begins.

    """

    player_preload_on: Annotated[
        Optional[bool], pydantic.Field(alias="playerPreloadOn")
    ] = None
    r"""Player Preload On indicates whether the player is configured to preload the video content upon page load.

    """

    player_remote_played: Annotated[
        Optional[bool], pydantic.Field(alias="playerRemotePlayed")
    ] = None
    r"""Player Remote Played specifies if the video is being remotely played to devices such as AirPlay or Chromecast, obtained from the SDK.

    """

    player_resolution: Annotated[
        OptionalNullable[str], pydantic.Field(alias="playerResolution")
    ] = UNSET
    r"""Player Resolution refers to the resolution of the video player window or viewport where the video content is being displayed.

    """

    player_software_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="playerSoftwareName")
    ] = UNSET
    r"""Represents the name of the video player software or framework used for playback (for example, HTML5, HLS.js, Shaka Player).

    """

    player_software_version: Annotated[
        OptionalNullable[str], pydantic.Field(alias="playerSoftwareVersion")
    ] = UNSET
    r"""Player Software Version indicates the version number of the player software installed.

    """

    player_source_domain: Annotated[
        OptionalNullable[str], pydantic.Field(alias="playerSourceDomain")
    ] = UNSET
    r"""Specifies the domain or source from which the player was loaded or embedded (for example, stream.fastpix.io or a customer’s custom domain). This helps identify the playback origin and differentiate between various deployment environments.

    """

    player_source_height: Annotated[
        OptionalNullable[int], pydantic.Field(alias="playerSourceHeight")
    ] = UNSET
    r"""Player Source Height denotes the vertical dimension, measured in pixels, of the source video content being transmitted to the player.

    """

    player_source_width: Annotated[
        OptionalNullable[int], pydantic.Field(alias="playerSourceWidth")
    ] = UNSET
    r"""Player Source Width represents the width of the source video as perceived by the player, typically measured in pixels.

    """

    player_version: Annotated[
        OptionalNullable[str], pydantic.Field(alias="playerVersion")
    ] = UNSET
    r"""Player Version indicates the version of the player used to render the video content. It is often utilized for performance comparison between different player versions.

    """

    player_view_count: Annotated[
        OptionalNullable[PlayerViewCount], pydantic.Field(alias="playerViewCount")
    ] = UNSET
    r"""Represents the total number of times the video player has been initialized or viewed for a specific session or video. This metric helps track playback engagement and identify view patterns across different players or sessions.

    """

    player_width: Annotated[
        OptionalNullable[int], pydantic.Field(alias="playerWidth")
    ] = UNSET
    r"""Player Width refers to the width of the player displayed within the webpage, measured in pixels.

    """

    property_id: Annotated[
        OptionalNullable[PropertyID], pydantic.Field(alias="propertyId")
    ] = UNSET
    r"""Represents the unique identifier assigned to a FastPix property, which is associated with a specific workspace or project. It helps link playback and analytics data to the correct property configuration.

    """

    quality_of_experience_score: Annotated[
        OptionalNullable[float], pydantic.Field(alias="qualityOfExperienceScore")
    ] = UNSET
    r"""Quality Of Experience Score quantifies the overall viewer experience based on various metrics, providing a decimal score to assess the quality of the viewing experience.

    """

    region: OptionalNullable[str] = UNSET
    r"""Region denotes the geographical region of the viewer accessing the video content.

    """

    render_quality_score: Annotated[
        OptionalNullable[float], pydantic.Field(alias="renderQualityScore")
    ] = UNSET
    r"""Render Quality Score is a decimal value representing the score indicating the perceived quality of the video.

    """

    session_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sessionId")] = (
        UNSET
    )
    r"""Session ID refers to the unique identifier tracking a viewers session within the FastPix platform.

    """

    sign: OptionalNullable[str] = UNSET
    r"""Represents a cryptographic signature used to verify the authenticity and integrity of the playback or API request within the FastPix platform. It ensures that the data has not been tampered with and originates from a trusted source.

    """

    stability_score: Annotated[
        OptionalNullable[float], pydantic.Field(alias="stabilityScore")
    ] = UNSET
    r"""Stability Score quantifies the smoothness of video playback, typically represented as a decimal value.

    """

    startup_score: Annotated[
        OptionalNullable[float], pydantic.Field(alias="startupScore")
    ] = UNSET
    r"""Startup Score evaluates the startup performance of the player, usually represented as a decimal value

    """

    sub_property_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="subPropertyId")
    ] = UNSET
    r"""Sub Property ID denotes the unique identifier assigned to FastPix properties, previously linked with a specific workspace.

    """

    total_startup_time: Annotated[
        OptionalNullable[int], pydantic.Field(alias="totalStartupTime")
    ] = UNSET
    r"""Represents the total time (in milliseconds) taken for the video player to start playback from the moment the user initiates the session. This includes loading, buffering, and initialization delays before the first frame is rendered.

    """

    updated_timestamp: Annotated[
        OptionalNullable[str], pydantic.Field(alias="updatedTimestamp")
    ] = UNSET
    r"""Updated Timestamp refers to when the record is updated to a particular Video.

    """

    used_full_screen: Annotated[
        Optional[bool], pydantic.Field(alias="usedFullScreen")
    ] = None
    r"""Used Fullscreen denotes whether the viewer utilized the full-screen mode while watching the video.

    """

    user_agent: Annotated[OptionalNullable[str], pydantic.Field(alias="userAgent")] = (
        UNSET
    )
    r"""User Agent represents the user agent string transmitted by the viewers device to identify itself to the server, typically including information about the device and browser.

    """

    video_content_type: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoContentType")
    ] = UNSET
    r"""Video Content Type specifies the classification of the video content.

    """

    video_duration: Annotated[
        OptionalNullable[int], pydantic.Field(alias="videoDuration")
    ] = UNSET
    r"""Video Duration represents the length of the video, provided in milliseconds, typically supplied to FastPix through custom metadata.

    """

    video_encoding_variant: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoEncodingVariant")
    ] = UNSET
    r"""Indicates the specific encoding variant or rendition of the video being played, such as resolution, bitrate, or codec type. This helps identify which encoded version of the video was selected for playback.

    """

    video_id: Annotated[OptionalNullable[str], pydantic.Field(alias="videoId")] = UNSET
    r"""Video ID refers to an internal identifier assigned by the user or system to uniquely identify a particular video.

    """

    video_language: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoLanguage")
    ] = UNSET
    r"""Video Language denotes the primary audio language of the video content, assuming it remains unchanged after playback initiation.

    """

    video_producer: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoProducer")
    ] = UNSET
    r"""Specifies the creator or source responsible for producing the video content.

    """

    video_resolution: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoResolution")
    ] = UNSET
    r"""Video Resolution refers to the resolution of the video being played.

    """

    video_series: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoSeries")
    ] = UNSET
    r"""Video Series denotes the name of a series to which the video content belongs.

    """

    video_source_domain: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoSourceDomain")
    ] = UNSET
    r"""Video Source Domain identifies the domain from which the video source originates.

    """

    video_source_duration: Annotated[
        OptionalNullable[int], pydantic.Field(alias="videoSourceDuration")
    ] = UNSET
    r"""Video Source Duration represents the duration of the video source content, measured in milliseconds.

    """

    video_source_hostname: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoSourceHostname")
    ] = UNSET
    r"""Video Source Hostname represents the hostname of the video.

    """

    video_source_stream_type: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoSourceStreamType")
    ] = UNSET
    r"""Video Source Stream Type denotes the type of stream used by the player, although it is currently unused.

    """

    video_source_type: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoSourceType")
    ] = UNSET
    r"""Video Source Type denotes the format of the video source as determined by the player.

    """

    video_source_url: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoSourceUrl")
    ] = UNSET
    r"""Video Source URL refers to the URL of the video source accessed by the player.

    """

    video_startup_failed: Annotated[
        Optional[bool], pydantic.Field(alias="videoStartupFailed")
    ] = None
    r"""Video Startup Failure is a boolean metric indicating whether a viewer encountered an error before the first frame of the video commenced playback.

    """

    video_startup_time: Annotated[
        OptionalNullable[int], pydantic.Field(alias="videoStartupTime")
    ] = UNSET
    r"""Video Startup Time measures the duration, in milliseconds, from the initialization of the player within the webpage to its readiness to receive further instructions.

    """

    video_title: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoTitle")
    ] = UNSET
    r"""Video Title refers to the title of the video content being viewed.

    """

    video_variant_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoVariantId")
    ] = UNSET
    r"""Represents the unique identifier for the specific video variant or rendition being played. Each variant corresponds to a particular encoding configuration, such as resolution or bitrate, used for adaptive streaming and performance tracking.

    """

    video_variant_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="videoVariantName")
    ] = UNSET
    r"""Specifies the human-readable name of the video variant or rendition being played (for example, “1080p H.264” or “720p AV1”). This helps identify the playback quality or encoding configuration selected during streaming.

    """

    view_end: Annotated[OptionalNullable[str], pydantic.Field(alias="viewEnd")] = UNSET
    r"""View End refers to the date and time, in Coordinated Universal Time (UTC), when the video viewing session concluded.

    """

    view_has_ad: Annotated[Optional[bool], pydantic.Field(alias="viewHasAd")] = None
    r"""View Has Ad is a boolean metric indicating whether an advertisement played or attempted to play during the video view.

    """

    view_has_error: Annotated[Optional[bool], pydantic.Field(alias="viewHasError")] = (
        None
    )
    r"""Indicates whether any playback error occurred during the video view. This boolean flag helps identify failed or interrupted playback sessions caused by player, network, or media-related issues.

    """

    view_id: Annotated[Optional[str], pydantic.Field(alias="viewId")] = None
    r"""View ID is a unique identifier assigned to each individual video viewing session.

    """

    view_max_playhead_position: Annotated[
        OptionalNullable[int], pydantic.Field(alias="viewMaxPlayheadPosition")
    ] = UNSET
    r"""View Max Playhead Position represents the furthest point reached by the playhead during the video view, measured in milliseconds.

    """

    view_page_url: Annotated[
        OptionalNullable[str], pydantic.Field(alias="viewPageUrl")
    ] = UNSET
    r"""View Page URL denotes the URL address of the web page where the video content is being accessed.

    """

    view_playing_time: Annotated[
        OptionalNullable[int], pydantic.Field(alias="viewPlayingTime")
    ] = UNSET
    r"""Playing Time denotes the total duration of time the video content was actively playing during the view, excluding time spent buffering, seeking, or joining.

    """

    view_seeked_count: Annotated[
        OptionalNullable[int], pydantic.Field(alias="viewSeekedCount")
    ] = UNSET
    r"""View Seeked Count signifies the number of times the viewer attempted to seek to a new location within the video.

    """

    view_seeked_duration: Annotated[
        OptionalNullable[int], pydantic.Field(alias="viewSeekedDuration")
    ] = UNSET
    r"""View Seeked Duration indicates the total duration of time spent waiting for playback to resume after the viewer seeks to a new location. Seek Latency metric in the Dashboard is derived by dividing this value by the view_seek_count.

    """

    view_session_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="viewSessionId")
    ] = UNSET
    r"""Represents the unique identifier assigned to a single playback session within FastPix. This ID is used to correlate all playback events, errors, and metrics that occur during the same viewing session.

    """

    view_start: Annotated[OptionalNullable[str], pydantic.Field(alias="viewStart")] = (
        UNSET
    )
    r"""View Start refers to the date and time, in Coordinated Universal Time (UTC), when the video viewing session commenced.

    """

    view_total_content_playback_time: Annotated[
        OptionalNullable[int], pydantic.Field(alias="viewTotalContentPlaybackTime")
    ] = UNSET
    r"""View Total Content Playback Time represents the cumulative duration of video content watched by the viewer, measured in milliseconds. This metric is internally utilized to calculate upscale and downscale percentages.

    """

    viewer_id: Annotated[OptionalNullable[str], pydantic.Field(alias="viewerId")] = (
        UNSET
    )
    r"""Viewer ID refers to a customer-defined identifier representing the viewer who is watching the video stream. It must be anonymized and not contain any personally identifiable information.

    """

    watch_time: Annotated[OptionalNullable[int], pydantic.Field(alias="watchTime")] = (
        UNSET
    )
    r"""Total Watch Time denotes the total duration of video content watched by the viewer, encompassing startup time, playing time, and potential rebuffering time, measured in milliseconds.

    """

    workspace_id: Annotated[Optional[str], pydantic.Field(alias="workspaceId")] = None
    r"""It is a unique identifier associated with a specific workspace within the FastPix platform.

    """

    events: Optional[List[Event]] = None
    r"""Events specifies the order of events journey of the video playback

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "asnId",
                "asnName",
                "averageBitrate",
                "avgDownscaling",
                "avgRequestLatency",
                "avgRequestThroughput",
                "avgUpscaling",
                "beaconDomain",
                "browserEngine",
                "browserName",
                "browserVersion",
                "bufferCount",
                "bufferFill",
                "bufferFrequency",
                "bufferRatio",
                "cdn",
                "city",
                "connectionType",
                "continent",
                "country",
                "countryCode",
                "custom",
                "deviceManufacturer",
                "deviceModel",
                "deviceName",
                "deviceType",
                "drmType",
                "droppedFrameCount",
                "errorCode",
                "errorContext",
                "errorId",
                "errorMessage",
                "exitBeforeVideoStart",
                "experimentName",
                "fpApiVersion",
                "fpEmbed",
                "fpEmbedVersion",
                "fpLiveStreamId",
                "fpPlaybackId",
                "fpSdk",
                "fpSdkVersion",
                "fpViewerId",
                "insertTimestamp",
                "ipAddress",
                "jumpLatency",
                "latitude",
                "liveStreamLatency",
                "longitude",
                "maxDownscaling",
                "maxRequestLatency",
                "maxUpscaling",
                "mediaId",
                "osName",
                "osVersion",
                "pageContext",
                "pageLoadTime",
                "playbackScore",
                "playerAutoplayOn",
                "playerHeight",
                "playerInitializationTime",
                "playerInstanceId",
                "playerLanguage",
                "playerName",
                "playerPoster",
                "playerPreloadOn",
                "playerRemotePlayed",
                "playerResolution",
                "playerSoftwareName",
                "playerSoftwareVersion",
                "playerSourceDomain",
                "playerSourceHeight",
                "playerSourceWidth",
                "playerVersion",
                "playerViewCount",
                "playerWidth",
                "propertyId",
                "qualityOfExperienceScore",
                "region",
                "renderQualityScore",
                "sessionId",
                "sign",
                "stabilityScore",
                "startupScore",
                "subPropertyId",
                "totalStartupTime",
                "updatedTimestamp",
                "usedFullScreen",
                "userAgent",
                "videoContentType",
                "videoDuration",
                "videoEncodingVariant",
                "videoId",
                "videoLanguage",
                "videoProducer",
                "videoResolution",
                "videoSeries",
                "videoSourceDomain",
                "videoSourceDuration",
                "videoSourceHostname",
                "videoSourceStreamType",
                "videoSourceType",
                "videoSourceUrl",
                "videoStartupFailed",
                "videoStartupTime",
                "videoTitle",
                "videoVariantId",
                "videoVariantName",
                "viewEnd",
                "viewHasAd",
                "viewHasError",
                "viewId",
                "viewMaxPlayheadPosition",
                "viewPageUrl",
                "viewPlayingTime",
                "viewSeekedCount",
                "viewSeekedDuration",
                "viewSessionId",
                "viewStart",
                "viewTotalContentPlaybackTime",
                "viewerId",
                "watchTime",
                "workspaceId",
                "events",
            ]
        )
        nullable_fields = set(
            [
                "asnId",
                "asnName",
                "averageBitrate",
                "avgDownscaling",
                "avgRequestLatency",
                "avgRequestThroughput",
                "avgUpscaling",
                "browserEngine",
                "browserName",
                "browserVersion",
                "bufferCount",
                "bufferFill",
                "bufferFrequency",
                "bufferRatio",
                "cdn",
                "city",
                "connectionType",
                "continent",
                "country",
                "countryCode",
                "deviceManufacturer",
                "deviceModel",
                "deviceName",
                "deviceType",
                "drmType",
                "droppedFrameCount",
                "errorCode",
                "errorContext",
                "errorId",
                "errorMessage",
                "experimentName",
                "fpApiVersion",
                "fpEmbed",
                "fpEmbedVersion",
                "fpLiveStreamId",
                "fpPlaybackId",
                "fpSdk",
                "fpSdkVersion",
                "fpViewerId",
                "jumpLatency",
                "latitude",
                "liveStreamLatency",
                "longitude",
                "maxDownscaling",
                "maxRequestLatency",
                "maxUpscaling",
                "mediaId",
                "osName",
                "pageContext",
                "pageLoadTime",
                "playbackScore",
                "playerHeight",
                "playerInitializationTime",
                "playerInstanceId",
                "playerLanguage",
                "playerName",
                "playerPoster",
                "playerResolution",
                "playerSoftwareName",
                "playerSoftwareVersion",
                "playerSourceDomain",
                "playerSourceHeight",
                "playerSourceWidth",
                "playerVersion",
                "playerViewCount",
                "playerWidth",
                "propertyId",
                "qualityOfExperienceScore",
                "region",
                "renderQualityScore",
                "sessionId",
                "sign",
                "stabilityScore",
                "startupScore",
                "subPropertyId",
                "totalStartupTime",
                "updatedTimestamp",
                "userAgent",
                "videoContentType",
                "videoDuration",
                "videoEncodingVariant",
                "videoId",
                "videoLanguage",
                "videoProducer",
                "videoResolution",
                "videoSeries",
                "videoSourceDomain",
                "videoSourceDuration",
                "videoSourceHostname",
                "videoSourceStreamType",
                "videoSourceType",
                "videoSourceUrl",
                "videoStartupTime",
                "videoTitle",
                "videoVariantId",
                "videoVariantName",
                "viewEnd",
                "viewMaxPlayheadPosition",
                "viewPageUrl",
                "viewPlayingTime",
                "viewSeekedCount",
                "viewSeekedDuration",
                "viewSessionId",
                "viewStart",
                "viewTotalContentPlaybackTime",
                "viewerId",
                "watchTime",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
