"""
This file is auto-generated.
Do not edit this file manually.
Your changes will be overwritten during the next generation.
"""

from __future__ import annotations
from fastpix_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ViewsByTopContentDetailsTypedDict(TypedDict):
    r"""Retrieves a list of the top video views"""

    video_title: NotRequired[str]
    r"""Title of the video"""
    views: NotRequired[int]
    r"""Total count of view sessions for a particular video content."""
    unique_views: NotRequired[int]
    r"""Total count of unique video viewers for particular video content."""


class ViewsByTopContentDetails(BaseModel):
    r"""Retrieves a list of the top video views"""

    video_title: Annotated[Optional[str], pydantic.Field(alias="videoTitle")] = None
    r"""Title of the video"""

    views: Optional[int] = None
    r"""Total count of view sessions for a particular video content."""

    unique_views: Annotated[Optional[int], pydantic.Field(alias="uniqueViews")] = None
    r"""Total count of unique video viewers for particular video content."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["videoTitle", "views", "uniqueViews"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
