import os
import sys
from datetime import datetime
from typing import Any, Dict

# Ensure we can import fastpix_python when running from test-project
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "src"))

from fastpix_python.types import UNSET, UNSET_SENTINEL  # type: ignore


def _is_unset(value: Any) -> bool:
    """Return True if a field value represents 'unset' in the SDK."""
    if value is UNSET or value == UNSET_SENTINEL:
        return True
    cls = getattr(value, "__class__", None)
    return cls is not None and cls.__name__ == "Unset"


def _get_field_order(model_cls) -> Any:
    """
    Best-effort: read any explicit field_order defined on the model's
    custom serializer so we can mirror the API's field ordering.
    Falls back to model_fields order if none is found.
    """
    import inspect
    import re

    serialize = getattr(model_cls, "serialize_model", None)
    if serialize is None:
        return None

    try:
        source = inspect.getsource(serialize)
    except (OSError, TypeError):
        return None

    # Look for: field_order = ["id", "name", ...]
    match = re.search(r"field_order\s*=\s*\[(.*?)\]", source, re.DOTALL)
    if not match:
        return None

    body = match.group(1)
    fields = re.findall(r'["\']([^"\']+)["\']', body)
    return fields or None


def _to_plain(obj: Any) -> Any:
    """
    Convert SDK models into plain Python types suitable for json.dumps,
    including only fields that the API actually returned, and preserving
    the API's field order when the model defines one.
    """
    if obj is None:
        return None

    if isinstance(obj, datetime):
        return obj.isoformat()

    if isinstance(obj, list):
        return [_to_plain(item) for item in obj]

    if isinstance(obj, dict):
        return {k: _to_plain(v) for k, v in obj.items()}

    # Handle Pydantic models generated by the SDK
    cls = type(obj)
    model_fields = getattr(cls, "model_fields", None)
    if model_fields is None:
        return obj

    # First collect all present fields
    collected: Dict[str, Any] = {}
    for field_name, field_info in model_fields.items():
        api_name = field_info.alias or field_name
        if not hasattr(obj, field_name):
            continue

        value = getattr(obj, field_name)
        if _is_unset(value):
            # Do not expose optional fields unless the API actually sent them
            continue

        collected[api_name] = _to_plain(value)

    # Then reorder using any explicit field_order the model defines
    field_order = _get_field_order(cls)
    if not field_order:
        return collected

    ordered: Dict[str, Any] = {}
    for name in field_order:
        if name in collected:
            ordered[name] = collected[name]

    # Append any extra fields that weren't listed in field_order
    for name, value in collected.items():
        if name not in ordered:
            ordered[name] = value

    return ordered


def to_api_payload(res: Any) -> Dict[str, Any]:
    """
    Public helper: turn a Fastpix SDK response into a JSON-ready dict that
    matches the API response:
      - correct field order
      - only fields actually returned by the API
      - datetimes converted to ISO strings
    """
    return {
        "success": res.success,
        "data": _to_plain(res.data),
    }

